export interface Kana {
  writing: string
  romaji: string
  alias: string[]
  category: string[]
  vowel: boolean
  consonant: boolean
  consonantVowelUnion: boolean
  family: string[]
}

export const hiragana = [
  {
    writing: 'あ',
    romaji: 'a',
    alias: ['a', 'A', 'あ', 'ア'],
    category: ['monograph', 'hiragana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'い',
    romaji: 'i',
    alias: ['i', 'I', 'い', 'イ'],
    category: ['monograph', 'hiragana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'う',
    romaji: 'u',
    alias: ['u', 'U', 'う', 'ウ'],
    category: ['monograph', 'hiragana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'え',
    romaji: 'e',
    alias: ['e', 'E', 'え', 'エ'],
    category: ['monograph', 'hiragana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'お',
    romaji: 'o',
    alias: ['o', 'O', 'お', 'オ'],
    category: ['monograph', 'hiragana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'か',
    romaji: 'ka',
    alias: ['ka', 'KA', 'か', 'カ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'き',
    romaji: 'ki',
    alias: ['ki', 'KI', 'き', 'キ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'く',
    romaji: 'ku',
    alias: ['ku', 'KU', 'く', 'ク'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'け',
    romaji: 'ke',
    alias: ['ke', 'KE', 'け', 'ケ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'こ',
    romaji: 'ko',
    alias: ['ko', 'KO', 'こ', 'コ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'きゃ',
    romaji: 'kya',
    alias: ['kya', 'KYA', 'きゃ', 'キャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'きゅ',
    romaji: 'kyu',
    alias: ['kyu', 'KYU', 'きゅ', 'キュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'きょ',
    romaji: 'kyo',
    alias: ['kyo', 'KYO', 'きょ', 'キョ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'さ',
    romaji: 'sa',
    alias: ['sa', 'SA', 'さ', 'サ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'し',
    romaji: 'shi',
    alias: ['shi', 'SHI', 'し', 'シ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'す',
    romaji: 'su',
    alias: ['su', 'SU', 'す', 'ス'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'せ',
    romaji: 'se',
    alias: ['se', 'SE', 'せ', 'セ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'そ',
    romaji: 'so',
    alias: ['so', 'SO', 'そ', 'ソ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'しゃ',
    romaji: 'sha',
    alias: ['sha', 'SHA', 'しゃ', 'シャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'しゅ',
    romaji: 'shu',
    alias: ['shu', 'SHU', 'しゅ', 'シュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'しょ',
    romaji: 'sho',
    alias: ['sho', 'SHO', 'しょ', 'ショ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'た',
    romaji: 'ta',
    alias: ['ta', 'TA', 'た', 'タ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ち',
    romaji: 'chi',
    alias: ['chi', 'CHI', 'ち', 'チ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'つ',
    romaji: 'tsu',
    alias: ['tsu', 'TSU', 'つ', 'ツ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'て',
    romaji: 'te',
    alias: ['te', 'TE', 'て', 'テ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'と',
    romaji: 'to',
    alias: ['to', 'TO', 'と', 'ト'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ちゃ',
    romaji: 'cha',
    alias: ['cha', 'CHA', 'ちゃ', 'チャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ちゅ',
    romaji: 'chu',
    alias: ['chu', 'CHU', 'ちゅ', 'チュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ちょ',
    romaji: 'cho',
    alias: ['cho', 'CHO', 'ちょ', 'チョ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'な',
    romaji: 'na',
    alias: ['na', 'NA', 'な', 'ナ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'に',
    romaji: 'ni',
    alias: ['ni', 'NI', 'に', 'ニ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ぬ',
    romaji: 'nu',
    alias: ['nu', 'NU', 'ぬ', 'ヌ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ね',
    romaji: 'ne',
    alias: ['ne', 'NE', 'ね', 'ネ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'の',
    romaji: 'no',
    alias: ['no', 'NO', 'の', 'ノ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'にゃ',
    romaji: 'nya',
    alias: ['nya', 'NYA', 'にゃ', 'ニャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'にゅ',
    romaji: 'nyu',
    alias: ['nyu', 'NYU', 'にゅ', 'ニュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'にょ',
    romaji: 'nyo',
    alias: ['nyo', 'NYO', 'にょ', 'ニョ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'は',
    romaji: 'ha',
    alias: ['ha', 'HA', 'は', 'ハ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ひ',
    romaji: 'hi',
    alias: ['hi', 'HI', 'ひ', 'ヒ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ふ',
    romaji: 'fu',
    alias: ['fu', 'FU', 'ふ', 'フ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'へ',
    romaji: 'he',
    alias: ['he', 'HE', 'へ', 'ヘ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ほ',
    romaji: 'ho',
    alias: ['ho', 'HO', 'ほ', 'ホ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ひゃ',
    romaji: 'hya',
    alias: ['hya', 'HYA', 'ひゃ', 'ヒャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ひゅ',
    romaji: 'hyu',
    alias: ['hyu', 'HYU', 'ひゅ', 'ヒュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ひょ',
    romaji: 'hyo',
    alias: ['hyo', 'HYO', 'ひょ', 'ヒョ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ま',
    romaji: 'ma',
    alias: ['ma', 'MA', 'ま', 'マ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'み',
    romaji: 'mi',
    alias: ['mi', 'MI', 'み', 'ミ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'む',
    romaji: 'mu',
    alias: ['mu', 'MU', 'む', 'ム'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'め',
    romaji: 'me',
    alias: ['me', 'ME', 'め', 'メ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'も',
    romaji: 'mo',
    alias: ['mo', 'MO', 'も', 'モ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'みゃ',
    romaji: 'mya',
    alias: ['mya', 'MYA', 'みゃ', 'ミャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'みゅ',
    romaji: 'myu',
    alias: ['myu', 'MYU', 'みゅ', 'ミュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'みょ',
    romaji: 'myo',
    alias: ['myo', 'MYO', 'みょ', 'ミョ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'や',
    romaji: 'ya',
    alias: ['ya', 'YA', 'や', 'ヤ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['y', 'Y', 'や', 'ヤ'],
  },
  {
    writing: 'ゆ',
    romaji: 'yu',
    alias: ['yu', 'YU', 'ゆ', 'ユ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['y', 'Y', 'や', 'ヤ'],
  },
  {
    writing: 'よ',
    romaji: 'yo',
    alias: ['yo', 'YO', 'よ', 'ヨ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['y', 'Y', 'や', 'ヤ'],
  },
  {
    writing: 'ら',
    romaji: 'ra',
    alias: ['ra', 'RA', 'ら', 'ラ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'り',
    romaji: 'ri',
    alias: ['ri', 'RI', 'り', 'リ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'る',
    romaji: 'ru',
    alias: ['ru', 'RU', 'る', 'ル'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'れ',
    romaji: 're',
    alias: ['re', 'RE', 'れ', 'レ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'ろ',
    romaji: 'ro',
    alias: ['ro', 'RO', 'ろ', 'ロ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'りゃ',
    romaji: 'rya',
    alias: ['rya', 'RYA', 'りゃ', 'リャ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'りゅ',
    romaji: 'ryu',
    alias: ['ryu', 'RYU', 'りゅ', 'リュ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'りょ',
    romaji: 'ryo',
    alias: ['ryo', 'RYO', 'りょ', 'リョ'],
    category: ['digraph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'わ',
    romaji: 'wa',
    alias: ['wa', 'WA', 'わ', 'ワ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['w', 'W', 'わ', 'ワ'],
  },
  {
    writing: 'を',
    romaji: 'wo',
    alias: ['wo', 'WO', 'を', 'ヲ'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['w', 'W', 'わ', 'ワ'],
  },
  {
    writing: 'ん',
    romaji: 'n',
    alias: ['n', 'N', 'ん', 'ン'],
    category: ['monograph', 'hiragana'],
    vowel: false,
    consonant: true,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'が',
    romaji: 'ga',
    alias: ['ga', 'GA', 'が', 'ガ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ぎ',
    romaji: 'gi',
    alias: ['gi', 'GI', 'ぎ', 'ギ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ぐ',
    romaji: 'gu',
    alias: ['gu', 'GU', 'ぐ', 'グ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'げ',
    romaji: 'ge',
    alias: ['ge', 'GE', 'げ', 'ゲ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ご',
    romaji: 'go',
    alias: ['go', 'GO', 'ご', 'ゴ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ぎゃ',
    romaji: 'gya',
    alias: ['gya', 'GYA', 'ぎゃ', 'ギャ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ぎゅ',
    romaji: 'gyu',
    alias: ['gyu', 'GYU', 'ぎゅ', 'ギュ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ぎょ',
    romaji: 'gyo',
    alias: ['gyo', 'GYO', 'ぎょ', 'ギョ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ざ',
    romaji: 'za',
    alias: ['za', 'ZA', 'ざ', 'ザ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'じ',
    romaji: 'ji',
    alias: ['ji', 'JI', 'じ', 'ジ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ず',
    romaji: 'zu',
    alias: ['zu', 'ZU', 'ず', 'ズ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ぜ',
    romaji: 'ze',
    alias: ['ze', 'ZE', 'ぜ', 'ゼ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ぞ',
    romaji: 'zo',
    alias: ['zo', 'ZO', 'ぞ', 'ゾ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'じゃ',
    romaji: 'ja',
    alias: ['ja', 'JA', 'じゃ', 'ジャ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'じゅ',
    romaji: 'ju',
    alias: ['ju', 'JU', 'じゅ', 'ジュ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'じょ',
    romaji: 'jo',
    alias: ['jo', 'JO', 'じょ', 'ジョ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'だ',
    romaji: 'da',
    alias: ['da', 'DA', 'だ', 'ダ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ぢ',
    romaji: 'ji',
    alias: ['ji', 'JI', 'ぢ', 'ヂ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'づ',
    romaji: 'zu',
    alias: ['zu', 'ZU', 'づ', 'ヅ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'で',
    romaji: 'de',
    alias: ['de', 'DE', 'で', 'デ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ど',
    romaji: 'do',
    alias: ['do', 'DO', 'ど', 'ド'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ぢゃ',
    romaji: 'ja',
    alias: ['ja', 'JA', 'ぢゃ', 'ヂャ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ぢゅ',
    romaji: 'ju',
    alias: ['ju', 'JU', 'ぢゅ', 'ヂュ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ぢょ',
    romaji: 'jo',
    alias: ['jo', 'JO', 'ぢょ', 'ヂョ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ば',
    romaji: 'ba',
    alias: ['ba', 'BA', 'ば', 'バ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'び',
    romaji: 'bi',
    alias: ['bi', 'BI', 'び', 'ビ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ぶ',
    romaji: 'bu',
    alias: ['bu', 'BU', 'ぶ', 'ブ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'べ',
    romaji: 'be',
    alias: ['be', 'BE', 'べ', 'ベ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ぼ',
    romaji: 'bo',
    alias: ['bo', 'BO', 'ぼ', 'ボ'],
    category: ['monograph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'びゃ',
    romaji: 'bya',
    alias: ['bya', 'BYA', 'びゃ', 'ビャ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'びゅ',
    romaji: 'byu',
    alias: ['byu', 'BYU', 'びゅ', 'ビュ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'びょ',
    romaji: 'byo',
    alias: ['byo', 'BYO', 'びょ', 'ビョ'],
    category: ['digraph', 'dakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ぱ',
    romaji: 'pa',
    alias: ['pa', 'PA', 'ぱ', 'パ'],
    category: ['monograph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぴ',
    romaji: 'pi',
    alias: ['pi', 'PI', 'ぴ', 'ピ'],
    category: ['monograph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぷ',
    romaji: 'pu',
    alias: ['pu', 'PU', 'ぷ', 'プ'],
    category: ['monograph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぺ',
    romaji: 'pe',
    alias: ['pe', 'PE', 'ぺ', 'ペ'],
    category: ['monograph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぽ',
    romaji: 'po',
    alias: ['po', 'PO', 'ぽ', 'ポ'],
    category: ['monograph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぴゃ',
    romaji: 'pya',
    alias: ['pya', 'PYA', 'ぴゃ', 'ピャ'],
    category: ['digraph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぴゅ',
    romaji: 'pyu',
    alias: ['pyu', 'PYU', 'ぴゅ', 'ピュ'],
    category: ['digraph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ぴょ',
    romaji: 'pyo',
    alias: ['pyo', 'PYO', 'ぴょ', 'ピョ'],
    category: ['digraph', 'handakuten', 'hiragana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
]

export const katakana = [
  {
    writing: 'ア',
    romaji: 'a',
    alias: ['a', 'A', 'あ', 'ア'],
    category: ['monograph', 'katakana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'イ',
    romaji: 'i',
    alias: ['i', 'I', 'い', 'イ'],
    category: ['monograph', 'katakana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'ウ',
    romaji: 'u',
    alias: ['u', 'U', 'う', 'ウ'],
    category: ['monograph', 'katakana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'エ',
    romaji: 'e',
    alias: ['e', 'E', 'え', 'エ'],
    category: ['monograph', 'katakana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'オ',
    romaji: 'o',
    alias: ['o', 'O', 'お', 'オ'],
    category: ['monograph', 'katakana'],
    vowel: true,
    consonant: false,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'カ',
    romaji: 'ka',
    alias: ['ka', 'KA', 'か', 'カ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'キ',
    romaji: 'ki',
    alias: ['ki', 'KI', 'き', 'キ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'ク',
    romaji: 'ku',
    alias: ['ku', 'KU', 'く', 'ク'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'ケ',
    romaji: 'ke',
    alias: ['ke', 'KE', 'け', 'ケ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'コ',
    romaji: 'ko',
    alias: ['ko', 'KO', 'こ', 'コ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'キャ',
    romaji: 'kya',
    alias: ['kya', 'KYA', 'きゃ', 'キャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'キュ',
    romaji: 'kyu',
    alias: ['kyu', 'KYU', 'きゅ', 'キュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'キョ',
    romaji: 'kyo',
    alias: ['kyo', 'KYO', 'きょ', 'キョ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['k', 'K', 'か', 'カ'],
  },
  {
    writing: 'サ',
    romaji: 'sa',
    alias: ['sa', 'SA', 'さ', 'サ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'シ',
    romaji: 'shi',
    alias: ['shi', 'SHI', 'し', 'シ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'ス',
    romaji: 'su',
    alias: ['su', 'SU', 'す', 'ス'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'セ',
    romaji: 'se',
    alias: ['se', 'SE', 'せ', 'セ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'ソ',
    romaji: 'so',
    alias: ['so', 'SO', 'そ', 'ソ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'シャ',
    romaji: 'sha',
    alias: ['sha', 'SHA', 'しゃ', 'シャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'シュ',
    romaji: 'shu',
    alias: ['shu', 'SHU', 'しゅ', 'シュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'ショ',
    romaji: 'sho',
    alias: ['sho', 'SHO', 'しょ', 'ショ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['s', 'S', 'さ', 'サ'],
  },
  {
    writing: 'タ',
    romaji: 'ta',
    alias: ['ta', 'TA', 'た', 'タ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'チ',
    romaji: 'chi',
    alias: ['chi', 'CHI', 'ち', 'チ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ツ',
    romaji: 'tsu',
    alias: ['tsu', 'TSU', 'つ', 'ツ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'テ',
    romaji: 'te',
    alias: ['te', 'TE', 'て', 'テ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ト',
    romaji: 'to',
    alias: ['to', 'TO', 'と', 'ト'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'チャ',
    romaji: 'cha',
    alias: ['cha', 'CHA', 'ちゃ', 'チャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'チュ',
    romaji: 'chu',
    alias: ['chu', 'CHU', 'ちゅ', 'チュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'チョ',
    romaji: 'cho',
    alias: ['cho', 'CHO', 'ちょ', 'チョ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['t', 'T', 'た', 'タ'],
  },
  {
    writing: 'ナ',
    romaji: 'na',
    alias: ['na', 'NA', 'な', 'ナ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ニ',
    romaji: 'ni',
    alias: ['ni', 'NI', 'に', 'ニ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ヌ',
    romaji: 'nu',
    alias: ['nu', 'NU', 'ぬ', 'ヌ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ネ',
    romaji: 'ne',
    alias: ['ne', 'NE', 'ね', 'ネ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ノ',
    romaji: 'no',
    alias: ['no', 'NO', 'の', 'ノ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ニャ',
    romaji: 'nya',
    alias: ['nya', 'NYA', 'にゃ', 'ニャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ニュ',
    romaji: 'nyu',
    alias: ['nyu', 'NYU', 'にゅ', 'ニュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ニョ',
    romaji: 'nyo',
    alias: ['nyo', 'NYO', 'にょ', 'ニョ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['n', 'N', 'な', 'ナ'],
  },
  {
    writing: 'ハ',
    romaji: 'ha',
    alias: ['ha', 'HA', 'は', 'ハ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ヒ',
    romaji: 'hi',
    alias: ['hi', 'HI', 'ひ', 'ヒ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'フ',
    romaji: 'fu',
    alias: ['fu', 'FU', 'ふ', 'フ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ヘ',
    romaji: 'he',
    alias: ['he', 'HE', 'へ', 'ヘ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ホ',
    romaji: 'ho',
    alias: ['ho', 'HO', 'ほ', 'ホ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ヒャ',
    romaji: 'hya',
    alias: ['hya', 'HYA', 'ひゃ', 'ヒャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ヒュ',
    romaji: 'hyu',
    alias: ['hyu', 'HYU', 'ひゅ', 'ヒュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'ヒョ',
    romaji: 'hyo',
    alias: ['hyo', 'HYO', 'ひょ', 'ヒョ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['h', 'H', 'は', 'ハ'],
  },
  {
    writing: 'マ',
    romaji: 'ma',
    alias: ['ma', 'MA', 'ま', 'マ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'ミ',
    romaji: 'mi',
    alias: ['mi', 'MI', 'み', 'ミ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'ム',
    romaji: 'mu',
    alias: ['mu', 'MU', 'む', 'ム'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'メ',
    romaji: 'me',
    alias: ['me', 'ME', 'め', 'メ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'モ',
    romaji: 'mo',
    alias: ['mo', 'MO', 'も', 'モ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'ミャ',
    romaji: 'mya',
    alias: ['mya', 'MYA', 'みゃ', 'ミャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'ミュ',
    romaji: 'myu',
    alias: ['myu', 'MYU', 'みゅ', 'ミュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'ミョ',
    romaji: 'myo',
    alias: ['myo', 'MYO', 'みょ', 'ミョ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['m', 'M', 'ま', 'マ'],
  },
  {
    writing: 'ヤ',
    romaji: 'ya',
    alias: ['ya', 'YA', 'や', 'ヤ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['y', 'Y', 'や', 'ヤ'],
  },
  {
    writing: 'ユ',
    romaji: 'yu',
    alias: ['yu', 'YU', 'ゆ', 'ユ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['y', 'Y', 'や', 'ヤ'],
  },
  {
    writing: 'ヨ',
    romaji: 'yo',
    alias: ['yo', 'YO', 'よ', 'ヨ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['y', 'Y', 'や', 'ヤ'],
  },
  {
    writing: 'ラ',
    romaji: 'ra',
    alias: ['ra', 'RA', 'ら', 'ラ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'リ',
    romaji: 'ri',
    alias: ['ri', 'RI', 'り', 'リ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'ル',
    romaji: 'ru',
    alias: ['ru', 'RU', 'る', 'ル'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'レ',
    romaji: 're',
    alias: ['re', 'RE', 'れ', 'レ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'ロ',
    romaji: 'ro',
    alias: ['ro', 'RO', 'ろ', 'ロ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'リャ',
    romaji: 'rya',
    alias: ['rya', 'RYA', 'りゃ', 'リャ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'リュ',
    romaji: 'ryu',
    alias: ['ryu', 'RYU', 'りゅ', 'リュ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'リョ',
    romaji: 'ryo',
    alias: ['ryo', 'RYO', 'りょ', 'リョ'],
    category: ['digraph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['r', 'R', 'ら', 'ラ'],
  },
  {
    writing: 'ワ',
    romaji: 'wa',
    alias: ['wa', 'WA', 'わ', 'ワ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['w', 'W', 'わ', 'ワ'],
  },
  {
    writing: 'ヲ',
    romaji: 'wo',
    alias: ['wo', 'WO', 'を', 'ヲ'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['w', 'W', 'わ', 'ワ'],
  },
  {
    writing: 'ン',
    romaji: 'n',
    alias: ['n', 'N', 'ん', 'ン'],
    category: ['monograph', 'katakana'],
    vowel: false,
    consonant: true,
    consonantVowelUnion: false,
    family: ['∅'],
  },
  {
    writing: 'ガ',
    romaji: 'ga',
    alias: ['ga', 'GA', 'が', 'ガ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ギ',
    romaji: 'gi',
    alias: ['gi', 'GI', 'ぎ', 'ギ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'グ',
    romaji: 'gu',
    alias: ['gu', 'GU', 'ぐ', 'グ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ゲ',
    romaji: 'ge',
    alias: ['ge', 'GE', 'げ', 'ゲ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ゴ',
    romaji: 'go',
    alias: ['go', 'GO', 'ご', 'ゴ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ギャ',
    romaji: 'gya',
    alias: ['gya', 'GYA', 'ぎゃ', 'ギャ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ギュ',
    romaji: 'gyu',
    alias: ['gyu', 'GYU', 'ぎゅ', 'ギュ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ギョ',
    romaji: 'gyo',
    alias: ['gyo', 'GYO', 'ぎょ', 'ギョ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['g', 'G', 'が', 'ガ'],
  },
  {
    writing: 'ザ',
    romaji: 'za',
    alias: ['za', 'ZA', 'ざ', 'ザ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ジ',
    romaji: 'ji',
    alias: ['ji', 'JI', 'じ', 'ジ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ズ',
    romaji: 'zu',
    alias: ['zu', 'ZU', 'ず', 'ズ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ゼ',
    romaji: 'ze',
    alias: ['ze', 'ZE', 'ぜ', 'ゼ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ゾ',
    romaji: 'zo',
    alias: ['zo', 'ZO', 'ぞ', 'ゾ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ジャ',
    romaji: 'ja',
    alias: ['ja', 'JA', 'じゃ', 'ジャ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ジュ',
    romaji: 'ju',
    alias: ['ju', 'JU', 'じゅ', 'ジュ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ジョ',
    romaji: 'jo',
    alias: ['jo', 'JO', 'じょ', 'ジョ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['z', 'Z', 'ざ', 'ザ'],
  },
  {
    writing: 'ダ',
    romaji: 'da',
    alias: ['da', 'DA', 'だ', 'ダ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ヂ',
    romaji: 'ji',
    alias: ['ji', 'JI', 'ぢ', 'ヂ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ヅ',
    romaji: 'zu',
    alias: ['zu', 'ZU', 'づ', 'ヅ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'デ',
    romaji: 'de',
    alias: ['de', 'DE', 'で', 'デ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ド',
    romaji: 'do',
    alias: ['do', 'DO', 'ど', 'ド'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ヂャ',
    romaji: 'ja',
    alias: ['ja', 'JA', 'ぢゃ', 'ヂャ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ヂュ',
    romaji: 'ju',
    alias: ['ju', 'JU', 'ぢゅ', 'ヂュ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'ヂョ',
    romaji: 'jo',
    alias: ['jo', 'JO', 'ぢょ', 'ヂョ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['d', 'D', 'だ', 'ダ'],
  },
  {
    writing: 'バ',
    romaji: 'ba',
    alias: ['ba', 'BA', 'ば', 'バ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ビ',
    romaji: 'bi',
    alias: ['bi', 'BI', 'び', 'ビ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ブ',
    romaji: 'bu',
    alias: ['bu', 'BU', 'ぶ', 'ブ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ベ',
    romaji: 'be',
    alias: ['be', 'BE', 'べ', 'ベ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ボ',
    romaji: 'bo',
    alias: ['bo', 'BO', 'ぼ', 'ボ'],
    category: ['monograph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ビャ',
    romaji: 'bya',
    alias: ['bya', 'BYA', 'びゃ', 'ビャ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ビュ',
    romaji: 'byu',
    alias: ['byu', 'BYU', 'びゅ', 'ビュ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'ビョ',
    romaji: 'byo',
    alias: ['byo', 'BYO', 'びょ', 'ビョ'],
    category: ['digraph', 'dakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['b', 'B', 'ば', 'バ'],
  },
  {
    writing: 'パ',
    romaji: 'pa',
    alias: ['pa', 'PA', 'ぱ', 'パ'],
    category: ['monograph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ピ',
    romaji: 'pi',
    alias: ['pi', 'PI', 'ぴ', 'ピ'],
    category: ['monograph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'プ',
    romaji: 'pu',
    alias: ['pu', 'PU', 'ぷ', 'プ'],
    category: ['monograph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ペ',
    romaji: 'pe',
    alias: ['pe', 'PE', 'ぺ', 'ペ'],
    category: ['monograph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ポ',
    romaji: 'po',
    alias: ['po', 'PO', 'ぽ', 'ポ'],
    category: ['monograph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ピャ',
    romaji: 'pya',
    alias: ['pya', 'PYA', 'ぴゃ', 'ピャ'],
    category: ['digraph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ピュ',
    romaji: 'pyu',
    alias: ['pyu', 'PYU', 'ぴゅ', 'ピュ'],
    category: ['digraph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
  {
    writing: 'ピョ',
    romaji: 'pyo',
    alias: ['pyo', 'PYO', 'ぴょ', 'ピョ'],
    category: ['digraph', 'handakuten', 'katakana'],
    vowel: false,
    consonant: false,
    consonantVowelUnion: true,
    family: ['p', 'P', 'ぱ', 'パ'],
  },
]
