// Complete list of vocabulary for the JLPT N5 – NIHONGO ICHIBAN
// https://nihongoichiban.com/2011/04/30/complete-list-of-vocabulary-for-the-jlpt-n5/

export const vocabulariesN5 = [
  {
    kanji: '',
    writing: 'ああ',
    furigana: 'ああ',
    romaji: 'ah',
    meaning: 'Ah!',
  },
  {
    kanji: '会う',
    writing: '会う',
    furigana: 'あう',
    romaji: 'au',
    meaning: 'to meet',
  },
  {
    kanji: '青い',
    writing: '青い',
    furigana: 'あおい',
    romaji: 'aoi',
    meaning: 'blue',
  },
  {
    kanji: '赤い',
    writing: '赤い',
    furigana: 'あかい',
    romaji: 'akai',
    meaning: 'red',
  },
  {
    kanji: '明るい',
    writing: '明るい',
    furigana: 'あかるい',
    romaji: 'akarui',
    meaning: 'light, bright',
  },
  {
    kanji: '秋',
    writing: '秋',
    furigana: 'あき',
    romaji: 'aki',
    meaning: 'autumn, fall',
  },
  {
    kanji: '開く',
    writing: '開く',
    furigana: 'あく',
    romaji: 'aku',
    meaning: 'open',
  },
  {
    kanji: '開ける',
    writing: '開ける',
    furigana: 'あける',
    romaji: 'akeru',
    meaning: 'to open',
  },
  {
    kanji: '',
    writing: 'あげる',
    furigana: 'あげる',
    romaji: 'ageru',
    meaning: 'to give',
  },
  {
    kanji: '朝',
    writing: '朝',
    furigana: 'あさ',
    romaji: 'asa',
    meaning: 'morning',
  },
  {
    kanji: '朝ご飯',
    writing: '朝ご飯',
    furigana: 'あさごはん',
    romaji: 'asagohan',
    meaning: 'breakfast',
  },
  {
    kanji: 'あさって',
    writing: 'あさって',
    furigana: 'あさって',
    romaji: 'asatte',
    meaning: 'the day after tomorrow',
  },
  {
    kanji: '足',
    writing: '足',
    furigana: 'あし',
    romaji: 'ashi',
    meaning: 'leg, foot',
  },
  {
    kanji: '明日',
    writing: '明日',
    furigana: 'あした',
    romaji: 'ashita',
    meaning: 'tomorrow',
  },
  {
    kanji: 'あそこ',
    writing: 'あそこ',
    furigana: 'あそこ',
    romaji: 'asoko',
    meaning: 'over there',
  },
  {
    kanji: '遊ぶ',
    writing: '遊ぶ',
    furigana: 'あそぶ',
    romaji: 'asobu',
    meaning: 'to play',
  },
  {
    kanji: '温かい',
    writing: '温かい',
    furigana: 'あたたかい',
    romaji: 'atatakai',
    meaning: 'warm',
  },
  {
    kanji: '頭',
    writing: '頭',
    furigana: 'あたま',
    romaji: 'atama',
    meaning: 'head',
  },
  {
    kanji: '新しい',
    writing: '新しい',
    furigana: 'あたらしい',
    romaji: 'atarashii',
    meaning: 'new',
  },
  {
    kanji: 'あちら',
    writing: 'あちら',
    furigana: 'あちら',
    romaji: 'achira',
    meaning: 'over there (polite)',
  },
  {
    kanji: '暑い',
    writing: '暑い',
    furigana: 'あつい',
    romaji: 'atsui',
    meaning: 'hot (air)',
  },
  {
    kanji: '厚い',
    writing: '厚い',
    furigana: 'あつい',
    romaji: 'atsui',
    meaning: 'thick',
  },
  {
    kanji: '後',
    writing: '後',
    furigana: 'あと',
    romaji: 'ato',
    meaning: 'later, after',
  },
  {
    kanji: '貴方',
    writing: '貴方',
    furigana: 'あなた',
    romaji: 'anata',
    meaning: 'you',
  },
  {
    kanji: '兄',
    writing: '兄',
    furigana: 'あに',
    romaji: 'ani',
    meaning: 'older brother',
  },
  {
    kanji: '姉',
    writing: '姉',
    furigana: 'あね',
    romaji: 'ane',
    meaning: 'older sister',
  },
  {
    kanji: 'あの',
    writing: 'あの',
    furigana: 'あの',
    romaji: 'ano',
    meaning: 'that (over there)',
  },
  {
    kanji: 'あの',
    writing: 'あの',
    furigana: 'あの',
    romaji: 'ano',
    meaning: 'well, then',
  },
  {
    kanji: 'アパート',
    writing: 'アパート',
    furigana: 'アパート',
    romaji: 'apaato',
    meaning: 'apartment',
  },
  {
    kanji: '浴びる',
    writing: '浴びる',
    furigana: 'あびる',
    romaji: 'abiru',
    meaning: 'to take a shower',
  },
  {
    kanji: '危ない',
    writing: '危ない',
    furigana: 'あぶない',
    romaji: 'abunai',
    meaning: 'dangerous',
  },
  {
    kanji: '甘い',
    writing: '甘い',
    furigana: 'あまい',
    romaji: 'amai',
    meaning: 'sweet',
  },
  {
    kanji: 'あまり',
    writing: 'あまり',
    furigana: 'あまり',
    romaji: 'amari',
    meaning: 'not so',
  },
  {
    kanji: '雨',
    writing: '雨',
    furigana: 'あめ',
    romaji: 'ame',
    meaning: 'rain',
  },
  {
    kanji: '洗う',
    writing: '洗う',
    furigana: 'あらう',
    romaji: 'arau',
    meaning: 'to wash',
  },
  {
    kanji: '有る',
    writing: '有る',
    furigana: 'ある',
    romaji: 'aru',
    meaning: 'to be, to exist',
  },
  {
    kanji: 'ある',
    writing: 'ある',
    furigana: 'ある',
    romaji: 'aru',
    meaning: 'to possess',
  },
  {
    kanji: '歩く',
    writing: '歩く',
    furigana: 'あるく',
    romaji: 'aruku',
    meaning: 'to walk',
  },
  {
    kanji: 'あれ',
    writing: 'あれ',
    furigana: 'あれ',
    romaji: 'are',
    meaning: 'that one',
  },
  {
    kanji: '良い',
    writing: '良い',
    furigana: 'いい / よい',
    romaji: 'ii, yoi',
    meaning: 'good',
  },
  {
    kanji: 'いいえ',
    writing: 'いいえ',
    furigana: 'いいえ',
    romaji: 'iie',
    meaning: 'no',
  },
  {
    kanji: '言う',
    writing: '言う',
    furigana: 'いう',
    romaji: 'iu',
    meaning: 'to say, to tell',
  },
  {
    kanji: '家',
    writing: '家',
    furigana: 'いえ',
    romaji: 'ie',
    meaning: 'house, home',
  },
  {
    kanji: '行く',
    writing: '行く',
    furigana: 'いく',
    romaji: 'iku',
    meaning: 'to go',
  },
  {
    kanji: 'いくつ',
    writing: 'いくつ',
    furigana: 'いくつ',
    romaji: 'ikutsu',
    meaning: 'how many, how old',
  },
  {
    kanji: 'いくら',
    writing: 'いくら',
    furigana: 'いくら',
    romaji: 'ikura',
    meaning: 'how much',
  },
  {
    kanji: '池',
    writing: '池',
    furigana: 'いけ',
    romaji: 'ike',
    meaning: 'pond',
  },
  {
    kanji: '医者',
    writing: '医者',
    furigana: 'いしゃ',
    romaji: 'isha',
    meaning: 'doctor',
  },
  {
    kanji: '椅子',
    writing: '椅子',
    furigana: 'いす',
    romaji: 'isu',
    meaning: 'chair',
  },
  {
    kanji: '忙しい',
    writing: '忙しい',
    furigana: 'いそがしい',
    romaji: 'isogashii',
    meaning: 'to be busy',
  },
  {
    kanji: '痛い',
    writing: '痛い',
    furigana: 'いたい',
    romaji: 'itai',
    meaning: 'to be painful',
  },
  {
    kanji: '一',
    writing: '一',
    furigana: 'いち',
    romaji: 'ichi',
    meaning: 'one',
  },
  {
    kanji: '一日',
    writing: '一日',
    furigana: 'いちにち',
    romaji: 'ichinichi',
    meaning: 'one day',
  },
  {
    kanji: '一番',
    writing: '一番',
    furigana: 'いちばん',
    romaji: 'ichiban',
    meaning: 'No. 1, the best, the first',
  },
  {
    kanji: 'いつ',
    writing: 'いつ',
    furigana: 'いつ',
    romaji: 'itsu',
    meaning: 'when',
  },
  {
    kanji: '五日',
    writing: '五日',
    furigana: 'いつか',
    romaji: 'itsuka',
    meaning: 'the 5th day of the month, 5 days',
  },
  {
    kanji: '一緒',
    writing: '一緒',
    furigana: 'いっしょ',
    romaji: 'issho',
    meaning: 'together',
  },
  {
    kanji: '五つ',
    writing: '五つ',
    furigana: 'いつつ',
    romaji: 'itsutsu',
    meaning: 'five',
  },
  {
    kanji: 'いつも',
    writing: 'いつも',
    furigana: 'いつも',
    romaji: 'itsumo',
    meaning: 'always',
  },
  {
    kanji: '今',
    writing: '今',
    furigana: 'いま',
    romaji: 'ima',
    meaning: 'now',
  },
  {
    kanji: '意味',
    writing: '意味',
    furigana: 'いみ',
    romaji: 'imi',
    meaning: 'meaning',
  },
  {
    kanji: '妹',
    writing: '妹',
    furigana: 'いもうと',
    romaji: 'imouto',
    meaning: 'someone’s younger sister',
  },
  {
    kanji: 'いや',
    writing: 'いや',
    furigana: 'いや',
    romaji: 'iya',
    meaning: 'not likable, unpleasant',
  },
  {
    kanji: '入口',
    writing: '入口',
    furigana: 'いりぐち',
    romaji: 'iriguchi',
    meaning: 'entrance',
  },
  {
    kanji: '',
    writing: 'いる',
    furigana: 'いる',
    romaji: 'iru',
    meaning: 'need, must have, be required',
  },
  {
    kanji: '',
    writing: 'いる',
    furigana: 'いる',
    romaji: 'iru',
    meaning: 'to exist',
  },
  {
    kanji: '入れる',
    writing: '入れる',
    furigana: 'いれる',
    romaji: 'ireru',
    meaning: 'to insert, to put in',
  },
  {
    kanji: '色',
    writing: '色',
    furigana: 'いろ',
    romaji: 'iro',
    meaning: 'color',
  },
  {
    kanji: '色々',
    writing: '色々',
    furigana: 'いろいろ',
    romaji: 'iroiro',
    meaning: 'various',
  },
  {
    kanji: '上',
    writing: '上',
    furigana: 'うえ',
    romaji: 'ue',
    meaning: 'top, on, above',
  },
  {
    kanji: '後ろ',
    writing: '後ろ',
    furigana: 'うしろ',
    romaji: 'ushiro',
    meaning: 'back, rear, behind',
  },
  {
    kanji: '薄い',
    writing: '薄い',
    furigana: 'うすい',
    romaji: 'usui',
    meaning: 'thin',
  },
  {
    kanji: '歌',
    writing: '歌',
    furigana: 'うた',
    romaji: 'uta',
    meaning: 'song',
  },
  {
    kanji: '歌う',
    writing: '歌う',
    furigana: 'うたう',
    romaji: 'utau',
    meaning: 'to sing',
  },
  {
    kanji: '内',
    writing: '内',
    furigana: 'うち',
    romaji: 'uchi',
    meaning: 'home',
  },
  {
    kanji: '生まれる',
    writing: '生まれる',
    furigana: 'うまれる',
    romaji: 'umareru',
    meaning: 'to be born',
  },
  {
    kanji: '海',
    writing: '海',
    furigana: 'うみ',
    romaji: 'umi',
    meaning: 'sea',
  },
  {
    kanji: '売る',
    writing: '売る',
    furigana: 'うる',
    romaji: 'uru',
    meaning: 'to sell',
  },
  {
    kanji: '上着',
    writing: '上着',
    furigana: 'うわぎ',
    romaji: 'uwagi',
    meaning: 'coat, jacket',
  },
  {
    kanji: '絵',
    writing: '絵',
    furigana: 'え',
    romaji: 'e',
    meaning: 'picture',
  },
  {
    kanji: '映画',
    writing: '映画',
    furigana: 'えいが',
    romaji: 'eiga',
    meaning: 'movie',
  },
  {
    kanji: '映画館',
    writing: '映画館',
    furigana: 'えいがかん',
    romaji: 'eigakan',
    meaning: 'cinema',
  },
  {
    kanji: '英語',
    writing: '英語',
    furigana: 'えいご',
    romaji: 'eigo',
    meaning: 'English language',
  },
  {
    kanji: 'ええ',
    writing: 'ええ',
    furigana: 'ええ',
    romaji: 'ee',
    meaning: 'Yes, I see',
  },
  {
    kanji: '駅',
    writing: '駅',
    furigana: 'えき',
    romaji: 'eki',
    meaning: 'station',
  },
  {
    kanji: 'エレベータ',
    writing: 'エレベータ',
    furigana: 'エレベータ',
    romaji: 'erebeeta',
    meaning: 'elevator',
  },
  {
    kanji: '円',
    writing: '円',
    furigana: 'えん',
    romaji: 'en',
    meaning: 'Yen',
  },
  {
    kanji: '鉛筆',
    writing: '鉛筆',
    furigana: 'えんぴつ',
    romaji: 'enpitsu',
    meaning: 'pencil',
  },
  {
    kanji: '御',
    writing: '御',
    furigana: 'お',
    romaji: 'o',
    meaning: 'honorific prefix',
  },
  {
    kanji: '美味しい',
    writing: '美味しい',
    furigana: 'おいしい',
    romaji: 'oishii',
    meaning: 'tasty, delicious',
  },
  {
    kanji: '大きい',
    writing: '大きい',
    furigana: 'おおきい',
    romaji: 'ookii',
    meaning: 'big',
  },
  {
    kanji: '',
    writing: 'おおぜい',
    furigana: 'おおぜい',
    romaji: ' oozei',
    meaning: 'many people',
  },
  {
    kanji: 'お母さん',
    writing: 'お母さん',
    furigana: 'おかあさん',
    romaji: 'okaasan',
    meaning: 'my own mother',
  },
  {
    kanji: 'お菓子',
    writing: 'お菓子',
    furigana: 'おかし',
    romaji: 'okashi',
    meaning: 'confectionary, cake',
  },
  {
    kanji: 'お金',
    writing: 'お金',
    furigana: 'おかね',
    romaji: 'okane',
    meaning: 'money',
  },
  {
    kanji: '起きる',
    writing: '起きる',
    furigana: 'おきる',
    romaji: 'okiru',
    meaning: 'to get up, to stand up',
  },
  {
    kanji: '置く',
    writing: '置く',
    furigana: 'おく',
    romaji: 'oku',
    meaning: 'to put, to place',
  },
  {
    kanji: '奥さん',
    writing: '奥さん',
    furigana: 'おくさん',
    romaji: 'okusan',
    meaning: 'someone’s wife',
  },
  {
    kanji: '送る',
    writing: '送る',
    furigana: 'おくる',
    romaji: 'okuru',
    meaning: 'to send',
  },
  {
    kanji: 'お酒',
    writing: 'お酒',
    furigana: 'おさけ',
    romaji: 'osake',
    meaning: 'alcohol, sake',
  },
  {
    kanji: 'お皿',
    writing: 'お皿',
    furigana: 'おさら',
    romaji: 'osara',
    meaning: 'plate',
  },
  {
    kanji: '伯父さん',
    writing: '伯父さん',
    furigana: 'おじさん',
    romaji: 'ojisan',
    meaning: 'uncle',
  },
  {
    kanji: 'おじいさん',
    writing: 'おじいさん',
    furigana: ' おじいさん',
    romaji: 'ojiisan',
    meaning: 'grand father',
  },
  {
    kanji: '押す',
    writing: '押す',
    furigana: 'おす',
    romaji: 'osu',
    meaning: 'to push',
  },
  {
    kanji: '遅い',
    writing: '遅い',
    furigana: 'おそい',
    romaji: 'osoi',
    meaning: 'late, slow',
  },
  {
    kanji: 'お茶',
    writing: 'お茶',
    furigana: 'おちゃ',
    romaji: 'ocha',
    meaning: 'tea',
  },
  {
    kanji: 'お手洗い',
    writing: 'お手洗い',
    furigana: 'おてあらい',
    romaji: 'otearai',
    meaning: 'toilet, lavatory',
  },
  {
    kanji: 'お父さん',
    writing: 'お父さん',
    furigana: 'おとうさん',
    romaji: 'otousan',
    meaning: 'father',
  },
  {
    kanji: '弟',
    writing: '弟',
    furigana: 'おとうと',
    romaji: 'otouto',
    meaning: 'someone’s younger brother',
  },
  {
    kanji: '男',
    writing: '男',
    furigana: 'おとこ',
    romaji: 'otoko',
    meaning: 'man',
  },
  {
    kanji: '男の子',
    writing: '男の子',
    furigana: 'おとこのこ',
    romaji: 'otokonoko',
    meaning: 'boy',
  },
  {
    kanji: '一昨日',
    writing: '一昨日',
    furigana: 'おととい',
    romaji: 'ototoi',
    meaning: 'the day before yesterday',
  },
  {
    kanji: '一昨年',
    writing: '一昨年',
    furigana: 'おととし',
    romaji: 'ototoshi',
    meaning: 'the year before last',
  },
  {
    kanji: '大人',
    writing: '大人',
    furigana: 'おとな',
    romaji: 'otona',
    meaning: 'adult',
  },
  {
    kanji: 'お腹',
    writing: 'お腹',
    furigana: 'おなか',
    romaji: 'onaka',
    meaning: 'stomach',
  },
  {
    kanji: '同じ',
    writing: '同じ',
    furigana: 'おなじ',
    romaji: 'onaji',
    meaning: 'same',
  },
  {
    kanji: 'お兄さん',
    writing: 'お兄さん',
    furigana: 'おにいさん',
    romaji: 'oniisan',
    meaning: 'someone’s elder brother',
  },
  {
    kanji: 'お姉さん',
    writing: 'お姉さん',
    furigana: 'おねえさん',
    romaji: 'oneesan',
    meaning: 'someone’s elder sister',
  },
  {
    kanji: '伯母さん',
    writing: '伯母さん',
    furigana: 'おばさん',
    romaji: 'obasan',
    meaning: 'aunt',
  },
  {
    kanji: '',
    writing: 'おばあさん',
    furigana: 'おばあさん',
    romaji: 'obaasan',
    meaning: 'grandmother',
  },
  {
    kanji: 'お弁当',
    writing: 'お弁当',
    furigana: 'おべんとう',
    romaji: 'obentou',
    meaning: 'lunchbox',
  },
  {
    kanji: '覚える',
    writing: '覚える',
    furigana: 'おぼえる',
    romaji: 'oboeru',
    meaning: 'to memorize, to remember',
  },
  {
    kanji: '重い',
    writing: '重い',
    furigana: 'おもい',
    romaji: 'omoi',
    meaning: 'heavy',
  },
  {
    kanji: '面白い',
    writing: '面白い',
    furigana: 'おもしろい',
    romaji: 'omoshiroi',
    meaning: 'interesting, funny',
  },
  {
    kanji: '泳ぐ',
    writing: '泳ぐ',
    furigana: 'およぐ',
    romaji: 'oyogu',
    meaning: 'to swim',
  },
  {
    kanji: '降りる',
    writing: '降りる',
    furigana: 'おりる',
    romaji: 'oriru',
    meaning: 'to get off',
  },
  {
    kanji: '終わる',
    writing: '終わる',
    furigana: 'おわる',
    romaji: 'owaru',
    meaning: 'to end',
  },
  {
    kanji: '音楽',
    writing: '音楽',
    furigana: 'おんがく',
    romaji: 'ongaku',
    meaning: 'music',
  },
  {
    kanji: '女',
    writing: '女',
    furigana: 'おんな',
    romaji: 'onna',
    meaning: 'woman',
  },
  {
    kanji: '女の子',
    writing: '女の子',
    furigana: 'おんなのこ',
    romaji: 'onnanoko',
    meaning: 'girl',
  },
  {
    kanji: '〜回',
    writing: '〜回',
    furigana: '〜かい',
    romaji: '~kai',
    meaning: '~times',
  },
  {
    kanji: '〜階',
    writing: '〜階',
    furigana: '〜かい',
    romaji: '~kai',
    meaning: '~floor',
  },
  {
    kanji: '外国',
    writing: '外国',
    furigana: 'がいこく',
    romaji: 'gaikoku',
    meaning: 'foreign country',
  },
  {
    kanji: '外国人',
    writing: '外国人',
    furigana: 'がいこくじん',
    romaji: 'gaikokujin',
    meaning: 'foreigner',
  },
  {
    kanji: '会社',
    writing: '会社',
    furigana: 'かいしゃ',
    romaji: 'kaisha',
    meaning: 'company, enterprise',
  },
  {
    kanji: '階段',
    writing: '階段',
    furigana: 'かいだん',
    romaji: 'kaidan',
    meaning: 'stairs',
  },
  {
    kanji: '買物',
    writing: '買物',
    furigana: 'かいもの',
    romaji: 'kaimono',
    meaning: 'shopping',
  },
  {
    kanji: '買う',
    writing: '買う',
    furigana: 'かう',
    romaji: 'kau',
    meaning: 'to buy',
  },
  {
    kanji: '返す',
    writing: '返す',
    furigana: 'かえす',
    romaji: 'kaesu',
    meaning: 'to return an object',
  },
  {
    kanji: '帰る',
    writing: '帰る',
    furigana: 'かえる',
    romaji: 'kaeru',
    meaning: 'to return home',
  },
  {
    kanji: '顔',
    writing: '顔',
    furigana: 'かお',
    romaji: 'kao',
    meaning: 'face',
  },
  {
    kanji: '',
    writing: 'かかる',
    furigana: 'かかる',
    romaji: 'kakaru',
    meaning: 'to take time, money',
  },
  {
    kanji: '鍵',
    writing: '鍵',
    furigana: 'かぎ',
    romaji: 'kagi',
    meaning: 'key',
  },
  {
    kanji: '書く',
    writing: '書く',
    furigana: 'かく',
    romaji: 'kaku',
    meaning: 'to write',
  },
  {
    kanji: '学生',
    writing: '学生',
    furigana: 'がくせい',
    romaji: 'gakusei',
    meaning: 'student',
  },
  {
    kanji: '〜か月',
    writing: '〜か月',
    furigana: '〜かげつ',
    romaji: '~kagetsu',
    meaning: '~ number of months',
  },
  {
    kanji: '',
    writing: 'かける',
    furigana: 'かける',
    romaji: 'kakeru',
    meaning: 'to wear',
  },
  {
    kanji: '',
    writing: 'かける',
    furigana: 'かける',
    romaji: 'kakeru',
    meaning: 'to make a phone call',
  },
  {
    kanji: '傘',
    writing: '傘',
    furigana: 'かさ',
    romaji: 'kasa',
    meaning: 'umbrella',
  },
  {
    kanji: '貸す',
    writing: '貸す',
    furigana: 'かす',
    romaji: 'kasu',
    meaning: 'to lend',
  },
  {
    kanji: '風',
    writing: '風',
    furigana: 'かぜ',
    romaji: 'kaze',
    meaning: 'wind',
  },
  {
    kanji: '風邪',
    writing: '風邪',
    furigana: 'かぜ',
    romaji: 'kaze',
    meaning: 'a cold',
  },
  {
    kanji: '家族',
    writing: '家族',
    furigana: 'かぞく',
    romaji: 'kazoku',
    meaning: 'family',
  },
  {
    kanji: '方',
    writing: '方',
    furigana: 'かた',
    romaji: 'kata',
    meaning: 'person (polite)',
  },
  {
    kanji: '片仮名',
    writing: '片仮名',
    furigana: 'かたかな',
    romaji: 'katakana',
    meaning: 'Katakana',
  },
  {
    kanji: '一月',
    writing: '一月',
    furigana: 'いちがつ',
    romaji: 'ichigatsu',
    meaning: 'January',
  },
  {
    kanji: '二月',
    writing: '二月',
    furigana: 'にがつ',
    romaji: 'nigatsu',
    meaning: 'February',
  },
  {
    kanji: '三月',
    writing: '三月',
    furigana: 'さんがつ',
    romaji: 'sangatsu',
    meaning: 'March',
  },
  {
    kanji: '四月',
    writing: '四月',
    furigana: 'しがつ',
    romaji: 'shigatsu',
    meaning: 'April',
  },
  {
    kanji: '五月',
    writing: '五月',
    furigana: 'ごがつ',
    romaji: 'gogatsu',
    meaning: 'May',
  },
  {
    kanji: '六月',
    writing: '六月',
    furigana: 'ろくがつ',
    romaji: 'rokugatsu',
    meaning: 'June',
  },
  {
    kanji: '七月',
    writing: '七月',
    furigana: 'しちがつ',
    romaji: 'shichigatsu',
    meaning: 'July',
  },
  {
    kanji: '八月',
    writing: '八月',
    furigana: 'はちがつ',
    romaji: 'hachigatsu',
    meaning: 'August',
  },
  {
    kanji: '九月',
    writing: '九月',
    furigana: 'くがつ',
    romaji: 'kugatsu',
    meaning: 'September',
  },
  {
    kanji: '十月',
    writing: '十月',
    furigana: 'じゅうがつ',
    romaji: 'juugatsu',
    meaning: 'October',
  },
  {
    kanji: '十一月',
    writing: '十一月',
    furigana: 'じゅういちがつ',
    romaji: 'juuichigatsu',
    meaning: 'November',
  },
  {
    kanji: '十二月',
    writing: '十二月',
    furigana: 'じゅうにがつ',
    romaji: 'juunigatsu',
    meaning: 'December',
  },
  {
    kanji: '学校',
    writing: '学校',
    furigana: 'がっこう',
    romaji: 'gakkou',
    meaning: 'school',
  },
  {
    kanji: '角',
    writing: '角',
    furigana: 'かど',
    romaji: 'kado',
    meaning: 'corner',
  },
  {
    kanji: '家内',
    writing: '家内',
    furigana: 'かない',
    romaji: 'kanai',
    meaning: 'my wife',
  },
  {
    kanji: '鞄',
    writing: '鞄',
    furigana: 'かばん',
    romaji: 'kaban',
    meaning: 'bag',
  },
  {
    kanji: '花瓶',
    writing: '花瓶',
    furigana: 'かびん',
    romaji: 'kabin',
    meaning: 'vase',
  },
  {
    kanji: '冠る',
    writing: '冠る',
    furigana: 'かぶる',
    romaji: 'kaburu',
    meaning: 'to put on a hat',
  },
  {
    kanji: '紙',
    writing: '紙',
    furigana: 'かみ',
    romaji: 'kami',
    meaning: 'paper',
  },
  {
    kanji: 'カメラ',
    writing: 'カメラ',
    furigana: 'かめら',
    romaji: 'kamera',
    meaning: 'camera',
  },
  {
    kanji: '火曜日',
    writing: '火曜日',
    furigana: 'かようび',
    romaji: 'kayoubi',
    meaning: 'Tuesday',
  },
  {
    kanji: '辛い',
    writing: '辛い',
    furigana: 'からい',
    romaji: 'karai',
    meaning: 'hot, spicy',
  },
  {
    kanji: '体',
    writing: '体',
    furigana: 'からだ',
    romaji: 'karada',
    meaning: 'body',
  },
  {
    kanji: '借りる',
    writing: '借りる',
    furigana: 'かりる',
    romaji: 'kariru',
    meaning: 'to borrow',
  },
  {
    kanji: '',
    writing: '〜がります',
    furigana: '〜がります',
    romaji: '~garimasu',
    meaning: '3rd person wants to',
  },
  {
    kanji: '軽い',
    writing: '軽い',
    furigana: 'かるい',
    romaji: 'karui',
    meaning: 'light (not heavy)',
  },
  {
    kanji: 'カレンダー',
    writing: 'カレンダー',
    furigana: 'カレンダー',
    romaji: 'karendaa',
    meaning: ' calendar',
  },
  {
    kanji: '川',
    writing: '川',
    furigana: 'かわ',
    romaji: 'kawa',
    meaning: 'river',
  },
  {
    kanji: '〜側',
    writing: '〜側',
    furigana: ' ~がわ',
    romaji: '~gawa',
    meaning: '~side',
  },
  {
    kanji: '可愛い',
    writing: '可愛い',
    furigana: 'かわいい',
    romaji: 'kawaii',
    meaning: 'cute, pretty',
  },
  {
    kanji: '漢字',
    writing: '漢字',
    furigana: 'かんじ',
    romaji: 'kanji',
    meaning: 'Kanji character',
  },
  {
    kanji: '木',
    writing: '木',
    furigana: 'き',
    romaji: 'ki',
    meaning: 'tree',
  },
  {
    kanji: '黄色い',
    writing: '黄色い',
    furigana: 'きいろい',
    romaji: 'kiiroi',
    meaning: 'yellow',
  },
  {
    kanji: '消える',
    writing: '消える',
    furigana: 'きえる',
    romaji: 'kieru',
    meaning: 'to go out, to vanish',
  },
  {
    kanji: '聞く',
    writing: '聞く',
    furigana: 'きく',
    romaji: 'kiku',
    meaning: 'to hear, to listen, to ask',
  },
  {
    kanji: '北',
    writing: '北',
    furigana: 'きた',
    romaji: 'kita',
    meaning: 'north',
  },
  {
    kanji: 'ギター',
    writing: 'ギター',
    furigana: 'ギター',
    romaji: 'gitaa',
    meaning: 'guitar',
  },
  {
    kanji: '汚い',
    writing: '汚い',
    furigana: 'きたない',
    romaji: 'kitanai',
    meaning: 'dirty',
  },
  {
    kanji: '喫茶店',
    writing: '喫茶店',
    furigana: 'きっさてん',
    romaji: 'kissaten',
    meaning: 'coffee shop',
  },
  {
    kanji: '切手',
    writing: '切手',
    furigana: 'きって',
    romaji: 'kitte',
    meaning: 'stamp',
  },
  {
    kanji: '切符',
    writing: '切符',
    furigana: 'きっぷ',
    romaji: 'kippu',
    meaning: 'ticket',
  },
  {
    kanji: '昨日',
    writing: '昨日',
    furigana: 'きのう',
    romaji: 'kinou',
    meaning: 'yesterday',
  },
  {
    kanji: '九',
    writing: '九',
    furigana: 'きゅう',
    romaji: 'kyuu',
    meaning: 'nine',
  },
  {
    kanji: '牛肉',
    writing: '牛肉',
    furigana: 'ぎゅうにく',
    romaji: 'gyuuniku',
    meaning: 'beef',
  },
  {
    kanji: '牛乳',
    writing: '牛乳',
    furigana: 'ぎゅうにゅう',
    romaji: 'gyuunyuu',
    meaning: 'milk',
  },
  {
    kanji: '今日',
    writing: '今日',
    furigana: 'きょう',
    romaji: 'kyou',
    meaning: 'today',
  },
  {
    kanji: '教室',
    writing: '教室',
    furigana: 'きょうしつ',
    romaji: 'kyoushitsu',
    meaning: 'class room',
  },
  {
    kanji: '兄弟',
    writing: '兄弟',
    furigana: 'きょうだい',
    romaji: 'kyoudai',
    meaning: 'siblings',
  },
  {
    kanji: '去年',
    writing: '去年',
    furigana: 'きょねん',
    romaji: 'kyonen',
    meaning: 'last year',
  },
  {
    kanji: '嫌い',
    writing: '嫌い',
    furigana: 'きらい',
    romaji: 'kirai',
    meaning: 'unpleasant, not likable',
  },
  {
    kanji: '切る',
    writing: '切る',
    furigana: 'きる',
    romaji: 'kiru',
    meaning: 'to cut',
  },
  {
    kanji: '着る',
    writing: '着る',
    furigana: 'きる',
    romaji: 'kiru',
    meaning: 'to wear, to put on',
  },
  {
    kanji: '来る',
    writing: '来る',
    furigana: 'くる',
    romaji: 'kuru',
    meaning: 'to come',
  },
  {
    kanji: '',
    writing: 'きれい',
    furigana: 'きれい',
    romaji: 'kirei',
    meaning: 'beautiful, clean',
  },
  {
    kanji: 'キロ',
    writing: 'キロ',
    furigana: 'キロ',
    romaji: 'kiro',
    meaning: 'kg',
  },
  {
    kanji: 'キロ',
    writing: 'キロ',
    furigana: 'キロ',
    romaji: 'kiro',
    meaning: 'km',
  },
  {
    kanji: '銀行',
    writing: '銀行',
    furigana: 'ぎんこう',
    romaji: 'ginkou',
    meaning: 'bank',
  },
  {
    kanji: '金曜日',
    writing: '金曜日',
    furigana: 'きんようび',
    romaji: 'kinyoubi',
    meaning: 'Friday',
  },

  {
    kanji: '九',
    writing: '九',
    furigana: 'く',
    romaji: 'ku',
    meaning: 'nine',
  },
  {
    kanji: '薬',
    writing: '薬',
    furigana: 'くすり',
    romaji: 'kusuri',
    meaning: 'medicine',
  },
  {
    kanji: '下さい',
    writing: '下さい',
    furigana: 'ください',
    romaji: 'kudasai',
    meaning: 'give me…',
  },
  {
    kanji: '果物',
    writing: '果物',
    furigana: 'くだもの',
    romaji: 'kudamono',
    meaning: 'fruit',
  },
  {
    kanji: '口',
    writing: '口',
    furigana: 'くち',
    romaji: 'kuchi',
    meaning: 'mouth',
  },
  {
    kanji: '靴',
    writing: '靴',
    furigana: 'くつ',
    romaji: 'kutsu',
    meaning: 'shoe',
  },
  {
    kanji: '靴下',
    writing: '靴下',
    furigana: 'くつした',
    romaji: 'kutsushita',
    meaning: 'socks',
  },
  {
    kanji: '国',
    writing: '国',
    furigana: 'くに',
    romaji: 'kuni',
    meaning: 'country',
  },
  {
    kanji: '曇り',
    writing: '曇り',
    furigana: 'くもり',
    romaji: 'kumori',
    meaning: 'cloudy weather',
  },
  {
    kanji: '暗い',
    writing: '暗い',
    furigana: 'くらい',
    romaji: 'kurai',
    meaning: 'dark',
  },
  {
    kanji: 'ぐらい',
    writing: 'ぐらい',
    furigana: 'ぐらい',
    romaji: 'gurai',
    meaning: 'about',
  },
  {
    kanji: 'クラス',
    writing: 'クラス',
    furigana: 'クラス',
    romaji: 'kurasu',
    meaning: 'class',
  },
  {
    kanji: 'グラム',
    writing: 'グラム',
    furigana: 'グラム',
    romaji: 'guramu',
    meaning: 'gram',
  },
  {
    kanji: '車',
    writing: '車',
    furigana: 'くるま',
    romaji: 'kuruma',
    meaning: 'car',
  },
  {
    kanji: '黒い',
    writing: '黒い',
    furigana: 'くろい',
    romaji: 'kuroi',
    meaning: 'black',
  },

  {
    kanji: '〜個',
    writing: '〜個',
    furigana: '〜こ',
    romaji: '~ko',
    meaning: 'counter for small objects',
  },
  {
    kanji: '五',
    writing: '五',
    furigana: 'ご',
    romaji: 'go',
    meaning: 'five',
  },
  {
    kanji: '〜語',
    writing: '〜語',
    furigana: '〜ご',
    romaji: '~go',
    meaning: '~ language',
  },
  {
    kanji: '公園',
    writing: '公園',
    furigana: 'こうえん',
    romaji: 'kouen',
    meaning: 'park, large garden',
  },
  {
    kanji: '交番',
    writing: '交番',
    furigana: 'こうばん',
    romaji: 'kouban',
    meaning: 'police box',
  },
  {
    kanji: '声',
    writing: '声',
    furigana: 'こえ',
    romaji: 'koe',
    meaning: 'voice',
  },
  {
    kanji: 'コート',
    writing: 'コート',
    furigana: 'コート',
    romaji: 'kooto',
    meaning: 'coat',
  },
  {
    kanji: 'ここ',
    writing: 'ここ',
    furigana: 'ここ',
    romaji: 'koko',
    meaning: 'here',
  },
  {
    kanji: '午後',
    writing: '午後',
    furigana: 'ごご',
    romaji: 'gogo',
    meaning: 'afternoon',
  },
  {
    kanji: '九日',
    writing: '九日',
    furigana: 'ここのか',
    romaji: 'kokonoka',
    meaning: '9th day of a month, 9 days',
  },
  {
    kanji: '九つ',
    writing: '九つ',
    furigana: 'ここのつ',
    romaji: 'kokonotsu',
    meaning: 'nine',
  },
  {
    kanji: 'ご主人',
    writing: 'ご主人',
    furigana: 'ごしゅじん',
    romaji: 'goshujin',
    meaning: 'someone else’s husband',
  },
  {
    kanji: '午前',
    writing: '午前',
    furigana: 'ごぜん',
    romaji: 'gozen',
    meaning: 'morning, a.m.',
  },
  {
    kanji: '答える',
    writing: '答える',
    furigana: 'こたえる',
    romaji: 'kotaeru',
    meaning: 'to answer',
  },
  {
    kanji: 'こちら',
    writing: 'こちら',
    furigana: 'こちら',
    romaji: 'kochira',
    meaning: 'this side, this place',
  },
  {
    kanji: 'コップ',
    writing: 'コップ',
    furigana: 'コップ',
    romaji: 'koppu',
    meaning: 'cup, glass',
  },
  {
    kanji: '今年',
    writing: '今年',
    furigana: 'ことし',
    romaji: 'kotoshi',
    meaning: 'this year',
  },
  {
    kanji: '言葉',
    writing: '言葉',
    furigana: 'ことば',
    romaji: 'kotoba',
    meaning: 'phrase, language',
  },
  {
    kanji: '子供',
    writing: '子供',
    furigana: 'こども',
    romaji: 'kodomo',
    meaning: 'child',
  },
  {
    kanji: 'この',
    writing: 'この',
    furigana: 'この',
    romaji: 'kono',
    meaning: 'this…',
  },
  {
    kanji: '御飯',
    writing: '御飯',
    furigana: 'ごはん',
    romaji: 'gohan',
    meaning: 'meal, cooked rice',
  },
  {
    kanji: '困る',
    writing: '困る',
    furigana: 'こまる',
    romaji: 'komaru',
    meaning: 'to be in trouble',
  },
  {
    kanji: 'これ',
    writing: 'これ',
    furigana: 'これ',
    romaji: 'kore',
    meaning: 'this',
  },
  {
    kanji: 'ごろ',
    writing: 'ごろ',
    furigana: 'ごろ',
    romaji: 'goro',
    meaning: 'around…',
  },
  {
    kanji: '今月',
    writing: '今月',
    furigana: 'こんげつ',
    romaji: 'kongetsu',
    meaning: 'this month',
  },
  {
    kanji: '今週',
    writing: '今週',
    furigana: 'こんしゅう',
    romaji: 'konshuu',
    meaning: 'this week',
  },
  {
    kanji: 'こんな',
    writing: 'こんな',
    furigana: 'こんな',
    romaji: 'konna',
    meaning: 'this sort of, this kind of',
  },
  {
    kanji: '今晩',
    writing: '今晩',
    furigana: 'こんばん',
    romaji: 'konban',
    meaning: 'this evening',
  },
  {
    kanji: 'さあ',
    writing: 'さあ',
    furigana: 'さあ',
    romaji: 'saa',
    meaning: 'well…',
  },
  {
    kanji: '〜歳',
    writing: '〜歳',
    furigana: '〜さい',
    romaji: '~sai',
    meaning: 'years old',
  },
  {
    kanji: '魚',
    writing: '魚',
    furigana: 'さかな',
    romaji: 'sakana',
    meaning: 'fish',
  },
  {
    kanji: '先',
    writing: '先',
    furigana: 'さき',
    romaji: 'saki',
    meaning: 'earlier, former',
  },
  {
    kanji: '咲く',
    writing: '咲く',
    furigana: 'さく',
    romaji: 'saku',
    meaning: 'to blossom',
  },
  {
    kanji: '作文',
    writing: '作文',
    furigana: 'さくぶん',
    romaji: 'sakubun',
    meaning: 'composition',
  },
  {
    kanji: '',
    writing: 'さす',
    furigana: 'さす',
    romaji: 'sasu',
    meaning: 'to open an umbrella',
  },
  {
    kanji: '冊',
    writing: '冊',
    furigana: '〜さつ',
    romaji: '~satsu',
    meaning: 'counter for books',
  },
  {
    kanji: '雑誌',
    writing: '雑誌',
    furigana: 'ざっし',
    romaji: 'zasshi',
    meaning: 'magazine',
  },
  {
    kanji: '砂糖',
    writing: '砂糖',
    furigana: 'さとう',
    romaji: 'satou',
    meaning: 'sugar',
  },
  {
    kanji: '寒い',
    writing: '寒い',
    furigana: 'さむい',
    romaji: 'samui',
    meaning: 'cold',
  },
  {
    kanji: '再来年',
    writing: '再来年',
    furigana: 'さらいねん',
    romaji: 'sarainen',
    meaning: 'the year after next year',
  },
  {
    kanji: '三',
    writing: '三',
    furigana: 'さん',
    romaji: 'san',
    meaning: 'three',
  },
  {
    kanji: '〜さん',
    writing: '〜さん',
    furigana: '〜さん',
    romaji: '~san',
    meaning: 'Mr., Mrs.',
  },
  {
    kanji: '散歩',
    writing: '散歩',
    furigana: 'さんぽ',
    romaji: 'sanpo',
    meaning: 'to take a walk',
  },

  {
    kanji: '四',
    writing: '四',
    furigana: 'し',
    romaji: 'shi',
    meaning: 'four',
  },
  {
    kanji: '〜時',
    writing: '〜時',
    furigana: '〜じ',
    romaji: '~ji',
    meaning: 'o’clock',
  },
  {
    kanji: '塩',
    writing: '塩',
    furigana: 'しお',
    romaji: 'shio',
    meaning: 'salt',
  },
  {
    kanji: 'しかし',
    writing: 'しかし',
    furigana: 'しかし',
    romaji: 'shikashi',
    meaning: 'however, but',
  },
  {
    kanji: '時間',
    writing: '時間',
    furigana: 'じかん',
    romaji: 'jikan',
    meaning: 'time',
  },
  {
    kanji: '〜時間',
    writing: '〜時間',
    furigana: '〜じかん',
    romaji: '~jikan',
    meaning: '~hours (classificator)',
  },
  {
    kanji: '仕事',
    writing: '仕事',
    furigana: 'しごと',
    romaji: 'shigoto',
    meaning: 'work',
  },
  {
    kanji: '辞書',
    writing: '辞書',
    furigana: 'じしょ',
    romaji: 'jisho',
    meaning: 'dictionary',
  },
  {
    kanji: '静か',
    writing: '静か',
    furigana: 'しずか',
    romaji: 'shizuka',
    meaning: 'quiet',
  },
  {
    kanji: '下',
    writing: '下',
    furigana: 'した',
    romaji: 'shita',
    meaning: 'under, below',
  },
  {
    kanji: '質問',
    writing: '質問',
    furigana: 'しつもん',
    romaji: 'shitsumon',
    meaning: 'question',
  },
  {
    kanji: '自転車',
    writing: '自転車',
    furigana: 'じてんしゃ',
    romaji: 'jitensha',
    meaning: 'bicycle',
  },
  {
    kanji: '自動車',
    writing: '自動車',
    furigana: 'じどうしゃ',
    romaji: 'jidousha',
    meaning: 'car, vehicle',
  },
  {
    kanji: '死ぬ',
    writing: '死ぬ',
    furigana: 'しぬ',
    romaji: 'shinu',
    meaning: 'to die, to pas away',
  },
  {
    kanji: '字引',
    writing: '字引',
    furigana: 'じびき',
    romaji: 'jibiki',
    meaning: 'dictionary',
  },
  {
    kanji: '自分',
    writing: '自分',
    furigana: 'じぶん',
    romaji: 'jibun',
    meaning: 'oneself',
  },
  {
    kanji: '閉まる',
    writing: '閉まる',
    furigana: 'しまる',
    romaji: 'shimaru',
    meaning: 'to close',
  },
  {
    kanji: '閉める',
    writing: '閉める',
    furigana: 'しめる',
    romaji: 'shimeru',
    meaning: 'to close',
  },
  {
    kanji: '締める',
    writing: '締める',
    furigana: 'しめる',
    romaji: 'shimeru',
    meaning: 'to fasten a seatbelt',
  },
  {
    kanji: 'じゃ',
    writing: 'じゃ',
    furigana: 'じゃ',
    romaji: 'ja',
    meaning: 'well, then',
  },
  {
    kanji: '写真',
    writing: '写真',
    furigana: 'しゃしん',
    romaji: 'shashin',
    meaning: 'photo',
  },
  {
    kanji: 'シャツ',
    writing: 'シャツ',
    furigana: 'シャツ',
    romaji: 'shatsu',
    meaning: 'shirt',
  },
  {
    kanji: '十',
    writing: '十',
    furigana: 'じゅう',
    romaji: 'juu',
    meaning: 'ten',
  },
  {
    kanji: '~週間',
    writing: '~週間',
    furigana: '〜しゅうかん',
    romaji: '~shuukan',
    meaning: '… weeks',
  },
  {
    kanji: '授業',
    writing: '授業',
    furigana: 'じゅぎょう',
    romaji: 'jugyou',
    meaning: 'lesson, class',
  },
  {
    kanji: '宿題',
    writing: '宿題',
    furigana: 'しゅくだい',
    romaji: 'shukudai',
    meaning: 'homework',
  },
  {
    kanji: '上手',
    writing: '上手',
    furigana: 'じょうず',
    romaji: 'jouzu',
    meaning: 'to be good at something',
  },
  {
    kanji: '丈夫',
    writing: '丈夫',
    furigana: 'じょうぶ',
    romaji: 'joubu',
    meaning: 'to be strong, durable',
  },
  {
    kanji: '醤油',
    writing: '醤油',
    furigana: 'しょうゆ',
    romaji: 'shouyu',
    meaning: 'soy sauce',
  },
  {
    kanji: '食堂',
    writing: '食堂',
    furigana: 'しょくどう',
    romaji: 'shokudou',
    meaning: 'dining room, canteen',
  },
  {
    kanji: '知る',
    writing: '知る',
    furigana: 'しる',
    romaji: 'shiru',
    meaning: 'to know',
  },
  {
    kanji: '白い',
    writing: '白い',
    furigana: 'しろい',
    romaji: 'shiroi',
    meaning: 'white',
  },
  {
    kanji: '〜人',
    writing: '〜人',
    furigana: '〜じん',
    romaji: '~jin',
    meaning: '~an, ~ese (nationality)',
  },
  {
    kanji: '新聞',
    writing: '新聞',
    furigana: 'しんぶん',
    romaji: 'shinbun',
    meaning: 'newspaper',
  },
  {
    kanji: '水曜日',
    writing: '水曜日',
    furigana: 'すいようび',
    romaji: 'suiyoubi',
    meaning: 'Wednesday',
  },
  {
    kanji: '吸う',
    writing: '吸う',
    furigana: 'すう',
    romaji: 'suu',
    meaning: 'to breathe, to smoke',
  },
  {
    kanji: 'スカート',
    writing: 'スカート',
    furigana: 'スカート',
    romaji: 'sukaato',
    meaning: 'skirt',
  },
  {
    kanji: '好き',
    writing: '好き',
    furigana: 'すき',
    romaji: 'suki',
    meaning: 'to like',
  },
  {
    kanji: '〜過ぎ',
    writing: '〜過ぎ',
    furigana: '〜すぎ',
    romaji: '~sugi',
    meaning: 'past, over',
  },
  {
    kanji: 'すぐに',
    writing: 'すぐに',
    furigana: 'すぐに',
    romaji: 'sugu ni',
    meaning: 'at once',
  },
  {
    kanji: '少し',
    writing: '少し',
    furigana: 'すこし',
    romaji: 'sukoshi',
    meaning: 'a little',
  },
  {
    kanji: '涼しい',
    writing: '涼しい',
    furigana: 'すずしい',
    romaji: 'suzushii',
    meaning: 'cool',
  },
  {
    kanji: '〜ずつ',
    writing: '〜ずつ',
    furigana: '〜ずつ',
    romaji: '~zutsu',
    meaning: 'each',
  },
  {
    kanji: 'ストーブ',
    writing: 'ストーブ',
    furigana: 'ストーブ',
    romaji: 'sutoobu',
    meaning: 'stove, heater',
  },
  {
    kanji: 'スプーン',
    writing: 'スプーン',
    furigana: 'スプーン',
    romaji: 'supuun',
    meaning: 'spoon',
  },
  {
    kanji: 'スポーツ',
    writing: 'スポーツ',
    furigana: 'スポーツ',
    romaji: 'supootsu',
    meaning: 'sports',
  },
  {
    kanji: 'ズボン',
    writing: 'ズボン',
    furigana: 'ズボン',
    romaji: 'zubon',
    meaning: 'trousers',
  },
  {
    kanji: '住む',
    writing: '住む',
    furigana: 'すむ',
    romaji: 'sumu',
    meaning: 'to live, to reside somewhere',
  },
  {
    kanji: 'スリッパ',
    writing: 'スリッパ',
    furigana: 'スリッパ',
    romaji: 'surippa',
    meaning: 'slipper',
  },
  {
    kanji: 'する',
    writing: 'する',
    furigana: 'する',
    romaji: 'suru',
    meaning: 'to do',
  },
  {
    kanji: '座る',
    writing: '座る',
    furigana: 'すわる',
    romaji: 'suwaru',
    meaning: 'to sit',
  },

  {
    kanji: '背',
    writing: '背',
    furigana: 'せい',
    romaji: 'sei',
    meaning: 'height',
  },
  {
    kanji: '生徒',
    writing: '生徒',
    furigana: 'せいと',
    romaji: 'seito',
    meaning: 'student',
  },
  {
    kanji: 'セーター',
    writing: 'セーター',
    furigana: 'セーター',
    romaji: 'seetaa',
    meaning: 'sweater',
  },
  {
    kanji: '石鹸',
    writing: '石鹸',
    furigana: 'せっけん',
    romaji: 'sekken',
    meaning: 'soap',
  },
  {
    kanji: '背広',
    writing: '背広',
    furigana: 'せびろ',
    romaji: 'sebiro',
    meaning: 'jacket, suit',
  },
  {
    kanji: '狭い',
    writing: '狭い',
    furigana: 'せまい',
    romaji: 'semai',
    meaning: 'narrow',
  },
  {
    kanji: 'ゼロ',
    writing: 'ゼロ',
    furigana: 'ゼロ',
    romaji: 'zero',
    meaning: 'zero',
  },
  {
    kanji: '千',
    writing: '千',
    furigana: 'せん',
    romaji: 'sen',
    meaning: '1,000, thousand',
  },
  {
    kanji: '先月',
    writing: '先月',
    furigana: 'せんげつ',
    romaji: 'sengetsu',
    meaning: 'last month',
  },
  {
    kanji: '先週',
    writing: '先週',
    furigana: 'せんしゅう',
    romaji: 'senshuu',
    meaning: 'last week',
  },
  {
    kanji: '先生',
    writing: '先生',
    furigana: 'せんせい',
    romaji: 'sensei',
    meaning: 'teacher',
  },
  {
    kanji: '洗濯',
    writing: '洗濯',
    furigana: 'せんたく',
    romaji: 'sentaku',
    meaning: 'washing, to wash',
  },
  {
    kanji: '全部',
    writing: '全部',
    furigana: 'ぜんぶ',
    romaji: 'zenbu',
    meaning: 'all',
  },
  {
    kanji: 'そう',
    writing: 'そう',
    furigana: 'そう',
    romaji: 'sou',
    meaning: 'so',
  },
  {
    kanji: '掃除',
    writing: '掃除',
    furigana: 'そうじ',
    romaji: 'souji',
    meaning: 'to clean',
  },
  {
    kanji: 'そうして',
    writing: 'そうして',
    furigana: 'そうして',
    romaji: 'soushite',
    meaning: 'and then',
  },
  {
    kanji: 'そこ',
    writing: 'そこ',
    furigana: 'そこ',
    romaji: 'soko',
    meaning: 'there',
  },
  {
    kanji: 'そちら',
    writing: 'そちら',
    furigana: 'そちら',
    romaji: 'sochira',
    meaning: 'there (polite)',
  },
  {
    kanji: '外',
    writing: '外',
    furigana: 'そと',
    romaji: 'soto',
    meaning: 'outside',
  },
  {
    kanji: 'その',
    writing: 'その',
    furigana: 'その',
    romaji: 'sono',
    meaning: 'that…',
  },
  {
    kanji: 'そば',
    writing: 'そば',
    furigana: 'そば',
    romaji: 'soba',
    meaning: 'next to',
  },
  {
    kanji: '空',
    writing: '空',
    furigana: 'そら',
    romaji: 'sora',
    meaning: 'sky',
  },
  {
    kanji: 'それ',
    writing: 'それ',
    furigana: 'それ',
    romaji: 'sore',
    meaning: 'that',
  },
  {
    kanji: 'それから',
    writing: 'それから',
    furigana: 'それから',
    romaji: 'sorekara',
    meaning: 'after that',
  },
  {
    kanji: 'それでは',
    writing: 'それでは',
    furigana: 'それでは',
    romaji: 'soredewa',
    meaning: 'then, well',
  },
  {
    kanji: '〜台',
    writing: '〜台',
    furigana: '〜だい',
    romaji: '~dai',
    meaning: 'counter for machines',
  },
  {
    kanji: '大学',
    writing: '大学',
    furigana: 'だいがく',
    romaji: 'daigaku',
    meaning: 'university',
  },
  {
    kanji: '大使館',
    writing: '大使館',
    furigana: 'たいしかん',
    romaji: 'taishikan',
    meaning: 'embassy',
  },
  {
    kanji: '大丈夫',
    writing: '大丈夫',
    furigana: 'だいじょうぶ',
    romaji: 'daijoubu',
    meaning: 'OK',
  },
  {
    kanji: '大好き',
    writing: '大好き',
    furigana: 'だいすき',
    romaji: 'daisuki',
    meaning: 'to be very fond of',
  },
  {
    kanji: '大切',
    writing: '大切',
    furigana: 'たいせつ',
    romaji: 'taisetsu',
    meaning: 'very important',
  },
  {
    kanji: '',
    writing: 'たいてい',
    furigana: 'たいてい',
    romaji: 'taitei',
    meaning: 'mostly, usually',
  },
  {
    kanji: '台所',
    writing: '台所',
    furigana: 'だいどころ',
    romaji: 'daidokoro',
    meaning: 'kitchen',
  },
  {
    kanji: '大変',
    writing: '大変',
    furigana: 'たいへん',
    romaji: 'taihen',
    meaning: 'very, serious',
  },
  {
    kanji: '高い',
    writing: '高い',
    furigana: 'たかい',
    romaji: 'takai',
    meaning: 'high, expensive',
  },
  {
    kanji: '沢山',
    writing: '沢山',
    furigana: 'たくさん',
    romaji: 'takusan',
    meaning: 'many, much',
  },
  {
    kanji: 'タクシー',
    writing: 'タクシー',
    furigana: 'タクシー',
    romaji: 'takushii',
    meaning: 'taxi',
  },
  {
    kanji: '出す',
    writing: '出す',
    furigana: 'だす',
    romaji: 'dasu',
    meaning: 'to take out, hand in',
  },
  {
    kanji: '~達',
    writing: '~達',
    furigana: '〜たち',
    romaji: '~tachi',
    meaning: 'more than one, and others',
  },
  {
    kanji: '立つ',
    writing: '立つ',
    furigana: 'たつ',
    romaji: 'tatsu',
    meaning: 'to stand',
  },
  {
    kanji: '建物',
    writing: '建物',
    furigana: 'たてもの',
    romaji: 'tatemono',
    meaning: 'building',
  },
  {
    kanji: '楽しい',
    writing: '楽しい',
    furigana: 'たのしい',
    romaji: 'tanoshii',
    meaning: 'pleasant, enjoyable',
  },
  {
    kanji: '頼む',
    writing: '頼む',
    furigana: 'たのむ',
    romaji: 'tanomu',
    meaning: 'to ask, to request',
  },
  {
    kanji: 'たばこ',
    writing: 'たばこ',
    furigana: 'たばこ',
    romaji: 'tabako',
    meaning: 'cigarette',
  },
  {
    kanji: '多分',
    writing: '多分',
    furigana: 'たぶん',
    romaji: 'tabun',
    meaning: 'perhaps, probably',
  },
  {
    kanji: '食べ物',
    writing: '食べ物',
    furigana: 'たべもの',
    romaji: 'tabemono',
    meaning: 'food',
  },
  {
    kanji: '食べる',
    writing: '食べる',
    furigana: 'たべる',
    romaji: 'taberu',
    meaning: 'to eat',
  },
  {
    kanji: '卵',
    writing: '卵',
    furigana: 'たまご',
    romaji: 'tamago',
    meaning: 'egg',
  },
  {
    kanji: '誰',
    writing: '誰',
    furigana: 'だれ',
    romaji: 'dare',
    meaning: 'who?',
  },
  {
    kanji: '誕生日',
    writing: '誕生日',
    furigana: 'たんじょうび',
    romaji: 'tanjoubi',
    meaning: 'birthday',
  },
  {
    kanji: 'だんだん',
    writing: 'だんだん',
    furigana: 'だんだん',
    romaji: 'dandan',
    meaning: 'gradually',
  },

  {
    kanji: '小さい',
    writing: '小さい',
    furigana: 'ちいさい',
    romaji: 'chiisai',
    meaning: 'small',
  },
  {
    kanji: '近い',
    writing: '近い',
    furigana: 'ちかい',
    romaji: 'chikai',
    meaning: 'near, close',
  },
  {
    kanji: '違う',
    writing: '違う',
    furigana: 'ちがう',
    romaji: 'chigau',
    meaning: 'different',
  },
  {
    kanji: '地下鉄',
    writing: '地下鉄',
    furigana: 'ちかてつ',
    romaji: 'chikatetsu',
    meaning: 'subway',
  },
  {
    kanji: '地図',
    writing: '地図',
    furigana: 'ちず',
    romaji: 'chizu',
    meaning: 'map',
  },
  {
    kanji: '父',
    writing: '父',
    furigana: 'ちち',
    romaji: 'chichi',
    meaning: 'my father',
  },
  {
    kanji: '茶色',
    writing: '茶色',
    furigana: 'ちゃいろ',
    romaji: 'chairo',
    meaning: 'brown',
  },
  {
    kanji: '茶碗',
    writing: '茶碗',
    furigana: 'ちゃわん',
    romaji: 'chawan',
    meaning: 'rice bowl',
  },
  {
    kanji: '〜中',
    writing: '〜中',
    furigana: '〜ちゅう',
    romaji: '~chuu',
    meaning: 'in the middle of',
  },
  {
    kanji: 'ちょうど',
    writing: 'ちょうど',
    furigana: 'ちょうど',
    romaji: 'choudo',
    meaning: 'just',
  },
  {
    kanji: 'ちょっと',
    writing: 'ちょっと',
    furigana: 'ちょっと',
    romaji: 'chotto',
    meaning: 'a little',
  },

  {
    kanji: '一日',
    writing: '一日',
    furigana: 'ついたち',
    romaji: 'tsuitachi',
    meaning: 'the 1st day of a month',
  },
  {
    kanji: '使う',
    writing: '使う',
    furigana: 'つかう',
    romaji: 'tsukau',
    meaning: 'to use',
  },
  {
    kanji: '疲れる',
    writing: '疲れる',
    furigana: 'つかれる',
    romaji: 'tsukareru',
    meaning: 'to get tired',
  },
  {
    kanji: '次',
    writing: '次',
    furigana: 'つぎ',
    romaji: 'tsugi',
    meaning: 'next',
  },
  {
    kanji: '着く',
    writing: '着く',
    furigana: 'つく',
    romaji: 'tsuku',
    meaning: 'to arrive',
  },
  {
    kanji: '机',
    writing: '机',
    furigana: 'つくえ',
    romaji: 'tsukue',
    meaning: 'table',
  },
  {
    kanji: '作る',
    writing: '作る',
    furigana: 'つくる',
    romaji: 'tsukuru',
    meaning: 'to make, to produce',
  },
  {
    kanji: '点ける',
    writing: '点ける',
    furigana: 'つける',
    romaji: 'tsukeru',
    meaning: 'to turn on',
  },
  {
    kanji: '勤める',
    writing: '勤める',
    furigana: 'つとめる',
    romaji: 'tsutomeru',
    meaning: 'to work for someone',
  },
  {
    kanji: '詰らない',
    writing: '詰らない',
    furigana: 'つまらない',
    romaji: 'tsumaranai',
    meaning: 'uninteresting',
  },
  {
    kanji: '冷たい',
    writing: '冷たい',
    furigana: 'つめたい',
    romaji: 'tsumetai',
    meaning: 'cold',
  },
  {
    kanji: '強い',
    writing: '強い',
    furigana: 'つよい',
    romaji: 'tsuyoi',
    meaning: 'strong',
  },

  {
    kanji: '手',
    writing: '手',
    furigana: 'て',
    romaji: 'te',
    meaning: 'hand',
  },
  {
    kanji: 'テープ',
    writing: 'テープ',
    furigana: 'テープ',
    romaji: 'teepu',
    meaning: 'tape',
  },
  {
    kanji: 'テープレコーダー',
    writing: 'テープレコーダー',
    furigana: 'テープレコーダー',
    romaji: ' teepu rekoodaa',
    meaning: 'tape recorder',
  },
  {
    kanji: 'テーブル',
    writing: 'テーブル',
    furigana: 'テーブル',
    romaji: 'teeburu',
    meaning: 'table',
  },
  {
    kanji: '出かける',
    writing: '出かける',
    furigana: 'でかける',
    romaji: 'dekakeru',
    meaning: 'to go out',
  },
  {
    kanji: '手紙',
    writing: '手紙',
    furigana: 'てがみ',
    romaji: 'tegami',
    meaning: 'letter',
  },
  {
    kanji: '出来る',
    writing: '出来る',
    furigana: 'できる',
    romaji: 'dekiru',
    meaning: 'can',
  },
  {
    kanji: '出口',
    writing: '出口',
    furigana: 'でぐち',
    romaji: 'deguchi',
    meaning: 'exit',
  },
  {
    kanji: 'テスト',
    writing: 'テスト',
    furigana: 'テスト',
    romaji: 'tesuto',
    meaning: 'test',
  },
  {
    kanji: 'では',
    writing: 'では',
    furigana: 'では',
    romaji: 'dewa',
    meaning: 'then, well',
  },
  {
    kanji: 'デパート',
    writing: 'デパート',
    furigana: 'デパート',
    romaji: 'depaato',
    meaning: 'department store',
  },
  {
    kanji: 'でも',
    writing: 'でも',
    furigana: 'でも',
    romaji: 'demo',
    meaning: 'but',
  },
  {
    kanji: '出ます',
    writing: '出ます',
    furigana: 'でます',
    romaji: 'demasu',
    meaning: 'to leave',
  },
  {
    kanji: 'テレビ',
    writing: 'テレビ',
    furigana: 'テレビ',
    romaji: 'terebi',
    meaning: 'TV',
  },
  {
    kanji: '天気',
    writing: '天気',
    furigana: 'てんき',
    romaji: 'tenki',
    meaning: 'weather',
  },
  {
    kanji: '電気',
    writing: '電気',
    furigana: 'でんき',
    romaji: 'denki',
    meaning: 'electricity',
  },
  {
    kanji: '電車',
    writing: '電車',
    furigana: 'でんしゃ',
    romaji: 'densha',
    meaning: 'train',
  },
  {
    kanji: '電話',
    writing: '電話',
    furigana: 'でんわ',
    romaji: 'denwa',
    meaning: 'phone',
  },
  {
    kanji: '戸',
    writing: '戸',
    furigana: 'と',
    romaji: 'to',
    meaning: 'door',
  },
  {
    kanji: '〜度',
    writing: '〜度',
    furigana: '〜ど',
    romaji: '~do',
    meaning: '~times, ~degree',
  },
  {
    kanji: 'ドア',
    writing: 'ドア',
    furigana: 'ドア',
    romaji: 'doa',
    meaning: 'door',
  },
  {
    kanji: 'トイレ',
    writing: 'トイレ',
    furigana: 'トイレ',
    romaji: 'toire',
    meaning: 'toilet, lavatory',
  },
  {
    kanji: 'どう',
    writing: 'どう',
    furigana: 'どう',
    romaji: 'dou',
    meaning: 'how?',
  },
  {
    kanji: 'どうして',
    writing: 'どうして',
    furigana: 'どうして',
    romaji: 'doushite',
    meaning: 'why?',
  },
  {
    kanji: 'どうぞ',
    writing: 'どうぞ',
    furigana: 'どうぞ',
    romaji: 'douzo',
    meaning: 'please, here you are',
  },
  {
    kanji: '動物',
    writing: '動物',
    furigana: 'どうぶつ',
    romaji: 'doubutsu',
    meaning: 'animal',
  },
  {
    kanji: 'どうも',
    writing: 'どうも',
    furigana: 'どうも',
    romaji: 'doumo',
    meaning: 'thanks',
  },
  {
    kanji: '十',
    writing: '十',
    furigana: 'とお',
    romaji: 'too',
    meaning: 'ten',
  },
  {
    kanji: '遠い',
    writing: '遠い',
    furigana: 'とおい',
    romaji: 'tooi',
    meaning: 'far',
  },
  {
    kanji: '十日',
    writing: '十日',
    furigana: 'とおか',
    romaji: 'tooka',
    meaning: 'the 10th day of a month, 10 days',
  },
  {
    kanji: '時々',
    writing: '時々',
    furigana: 'ときどき',
    romaji: 'tokidoki',
    meaning: 'sometimes',
  },
  {
    kanji: '時計',
    writing: '時計',
    furigana: 'とけい',
    romaji: 'tokei',
    meaning: 'watch, clock',
  },
  {
    kanji: 'どこ',
    writing: 'どこ',
    furigana: 'どこ',
    romaji: 'doko',
    meaning: 'where?',
  },
  {
    kanji: '所',
    writing: '所',
    furigana: 'ところ',
    romaji: 'tokoro',
    meaning: 'place',
  },
  {
    kanji: '図書館',
    writing: '図書館',
    furigana: 'としょかん',
    romaji: 'toshokan',
    meaning: 'library',
  },
  {
    kanji: 'どちら',
    writing: 'どちら',
    furigana: 'どちら',
    romaji: 'dochira',
    meaning: 'which, where (polite)',
  },
  {
    kanji: 'とても',
    writing: 'とても',
    furigana: 'とても',
    romaji: 'totemo',
    meaning: 'very much, quiet',
  },
  {
    kanji: 'どなた',
    writing: 'どなた',
    furigana: 'どなた',
    romaji: 'donata',
    meaning: 'who (polite)',
  },
  {
    kanji: '隣り',
    writing: '隣り',
    furigana: 'となり',
    romaji: 'tonari',
    meaning: 'next to',
  },
  {
    kanji: 'どの',
    writing: 'どの',
    furigana: 'どの',
    romaji: 'dono',
    meaning: 'which?',
  },
  {
    kanji: '飛ぶ',
    writing: '飛ぶ',
    furigana: 'とぶ',
    romaji: 'tobu',
    meaning: 'to fly',
  },
  {
    kanji: '止まる',
    writing: '止まる',
    furigana: 'とまる',
    romaji: 'tomaru',
    meaning: 'to stop',
  },
  {
    kanji: '友達',
    writing: '友達',
    furigana: 'ともだち',
    romaji: 'tomodachi',
    meaning: 'friend',
  },
  {
    kanji: '土曜日',
    writing: '土曜日',
    furigana: 'どようび',
    romaji: 'doyoubi',
    meaning: 'Saturday',
  },
  {
    kanji: '鳥',
    writing: '鳥',
    furigana: 'とり',
    romaji: 'tori',
    meaning: 'bird',
  },
  {
    kanji: '鶏肉',
    writing: '鶏肉',
    furigana: 'とりにく',
    romaji: 'toriniku',
    meaning: 'chicken meat',
  },
  {
    kanji: '取る',
    writing: '取る',
    furigana: 'とる',
    romaji: 'toru',
    meaning: 'to take',
  },
  {
    kanji: '撮る',
    writing: '撮る',
    furigana: 'とる',
    romaji: 'toru',
    meaning: 'to take a photo',
  },
  {
    kanji: 'どれ',
    writing: 'どれ',
    furigana: 'どれ',
    romaji: 'dore',
    meaning: 'which?',
  },
  {
    kanji: 'どんな',
    writing: 'どんな',
    furigana: 'どんな',
    romaji: 'donna',
    meaning: 'what kind of?',
  },

  {
    kanji: 'ナイフ',
    writing: 'ナイフ',
    furigana: 'ナイフ',
    romaji: 'naifu',
    meaning: 'knife',
  },
  {
    kanji: '中',
    writing: '中',
    furigana: 'なか',
    romaji: 'naka',
    meaning: 'inside',
  },
  {
    kanji: '長い',
    writing: '長い',
    furigana: 'ながい',
    romaji: 'nagai',
    meaning: 'long',
  },
  {
    kanji: '鳴く',
    writing: '鳴く',
    furigana: 'なく',
    romaji: 'naku',
    meaning: 'to sing, mew, moo',
  },
  {
    kanji: '夏',
    writing: '夏',
    furigana: 'なつ',
    romaji: 'natsu',
    meaning: 'summer',
  },
  {
    kanji: '夏休み',
    writing: '夏休み',
    furigana: 'なつやすみ',
    romaji: 'natsuyasumi',
    meaning: 'summer vacation',
  },
  {
    kanji: '〜など',
    writing: '〜など',
    furigana: '〜など',
    romaji: '~nado',
    meaning: 'and so on',
  },
  {
    kanji: '七つ',
    writing: '七つ',
    furigana: 'ななつ',
    romaji: 'nanatsu',
    meaning: 'seven',
  },
  {
    kanji: '何',
    writing: '何',
    furigana: 'なに',
    romaji: 'nani',
    meaning: 'what?',
  },
  {
    kanji: '七日',
    writing: '七日',
    furigana: 'なのか',
    romaji: 'nanoka',
    meaning: 'the 7th of a month, 7 days',
  },
  {
    kanji: '名前',
    writing: '名前',
    furigana: 'なまえ',
    romaji: 'namae',
    meaning: 'name',
  },
  {
    kanji: '習う',
    writing: '習う',
    furigana: 'ならう',
    romaji: 'narau',
    meaning: 'to learn',
  },
  {
    kanji: '並ぶ',
    writing: '並ぶ',
    furigana: 'ならぶ',
    romaji: 'narabu',
    meaning: 'to form a line',
  },
  {
    kanji: '並べる',
    writing: '並べる',
    furigana: 'ならべる',
    romaji: 'naraberu',
    meaning: 'to line up',
  },
  {
    kanji: '',
    writing: 'なる',
    furigana: 'なる',
    romaji: 'naru',
    meaning: 'to become',
  },

  {
    kanji: '二',
    writing: '二',
    furigana: 'に',
    romaji: 'ni',
    meaning: 'two',
  },
  {
    kanji: '賑やか',
    writing: '賑やか',
    furigana: 'にぎやか',
    romaji: 'nigiyaka',
    meaning: 'lively',
  },
  {
    kanji: 'お肉',
    writing: 'お肉',
    furigana: 'おにく',
    romaji: 'oniku',
    meaning: 'meat',
  },
  {
    kanji: '西',
    writing: '西',
    furigana: 'にし',
    romaji: 'nishi',
    meaning: 'west',
  },
  {
    kanji: '〜日',
    writing: '〜日',
    furigana: '〜にち',
    romaji: '~nichi',
    meaning: '…st, ..nd, ..th',
  },
  {
    kanji: '日曜日',
    writing: '日曜日',
    furigana: 'にちようび',
    romaji: 'nichiyoubi',
    meaning: 'Sunday',
  },
  {
    kanji: '荷物',
    writing: '荷物',
    furigana: 'にもつ',
    romaji: 'nimotsu',
    meaning: 'luggage',
  },
  {
    kanji: 'ニュース',
    writing: 'ニュース',
    furigana: 'ニュース',
    romaji: 'nyuusu',
    meaning: 'news',
  },
  {
    kanji: '庭',
    writing: '庭',
    furigana: 'にわ',
    romaji: 'niwa',
    meaning: 'garden',
  },
  {
    kanji: '〜人',
    writing: '〜人',
    furigana: '~にん',
    romaji: '~nin',
    meaning: '… people',
  },
  {
    kanji: '脱ぐ',
    writing: '脱ぐ',
    furigana: 'ぬぐ',
    romaji: 'nugu',
    meaning: 'to take off clothes',
  },
  {
    kanji: 'ネクタイ',
    writing: 'ネクタイ',
    furigana: 'ネクタイ',
    romaji: 'nekutai',
    meaning: 'necktie',
  },
  {
    kanji: '寝る',
    writing: '寝る',
    furigana: 'ねる',
    romaji: 'neru',
    meaning: 'to go to bed',
  },
  {
    kanji: '〜年',
    writing: '〜年',
    furigana: '〜ねん',
    romaji: '~nen',
    meaning: '~years',
  },

  {
    kanji: 'ノート',
    writing: 'ノート',
    furigana: 'ノート',
    romaji: 'nooto',
    meaning: 'notebook',
  },
  {
    kanji: '登る',
    writing: '登る',
    furigana: 'のぼる',
    romaji: 'noboru',
    meaning: 'to climb up',
  },
  {
    kanji: '飲物',
    writing: '飲物',
    furigana: 'のみもの',
    romaji: 'nomimono',
    meaning: 'drinks',
  },
  {
    kanji: '飲む',
    writing: '飲む',
    furigana: 'のむ',
    romaji: 'nomu',
    meaning: 'to drink',
  },
  {
    kanji: '乗る',
    writing: '乗る',
    furigana: 'のる',
    romaji: 'noru',
    meaning: 'to take, to ride',
  },

  {
    kanji: '歯',
    writing: '歯',
    furigana: 'は',
    romaji: 'ha',
    meaning: 'teeth',
  },
  {
    kanji: 'パーテイー',
    writing: 'パーテイー',
    furigana: 'パーテイー',
    romaji: 'paateii',
    meaning: 'party',
  },
  {
    kanji: 'はい',
    writing: 'はい',
    furigana: 'はい',
    romaji: 'hai',
    meaning: 'yes',
  },
  {
    kanji: '〜はい',
    writing: '〜はい',
    furigana: '〜はい',
    romaji: '~hai',
    meaning: 'cups of ~',
  },
  {
    kanji: '灰皿',
    writing: '灰皿',
    furigana: 'はいざら',
    romaji: 'haizara',
    meaning: 'ashtray',
  },
  {
    kanji: '入る',
    writing: '入る',
    furigana: 'はいる',
    romaji: 'hairu',
    meaning: 'to enter',
  },
  {
    kanji: '葉書',
    writing: '葉書',
    furigana: 'はがき',
    romaji: 'hagaki',
    meaning: 'postcard',
  },
  {
    kanji: '履く',
    writing: '履く',
    furigana: 'はく',
    romaji: 'haku',
    meaning: 'to put on shoes',
  },
  {
    kanji: '箱',
    writing: '箱',
    furigana: 'はこ',
    romaji: 'hako',
    meaning: 'box',
  },
  {
    kanji: '橋',
    writing: '橋',
    furigana: 'はし',
    romaji: 'hashi',
    meaning: 'bridge',
  },
  {
    kanji: '箸',
    writing: '箸',
    furigana: 'はし',
    romaji: 'hashi',
    meaning: 'chopsticks',
  },
  {
    kanji: '始まる',
    writing: '始まる',
    furigana: 'はじまる',
    romaji: 'hajimaru',
    meaning: 'to begin, to start',
  },
  {
    kanji: '始め',
    writing: '始め',
    furigana: 'はじめ',
    romaji: 'hajime',
    meaning: 'start, the beginning',
  },
  {
    kanji: '初めて',
    writing: '初めて',
    furigana: 'はじめて',
    romaji: 'hajimete',
    meaning: 'for the first time',
  },
  {
    kanji: '走る',
    writing: '走る',
    furigana: 'はしる',
    romaji: 'hashiru',
    meaning: 'to run',
  },
  {
    kanji: 'バス',
    writing: 'バス',
    furigana: 'バス',
    romaji: 'basu',
    meaning: 'bus',
  },
  {
    kanji: 'バター',
    writing: 'バター',
    furigana: 'バター',
    romaji: 'bataa',
    meaning: 'butter',
  },
  {
    kanji: '二十歳',
    writing: '二十歳',
    furigana: 'はたち',
    romaji: 'hatachi',
    meaning: '20 years old',
  },
  {
    kanji: '働く',
    writing: '働く',
    furigana: 'はたらく',
    romaji: 'hataraku',
    meaning: 'to work',
  },
  {
    kanji: '八',
    writing: '八',
    furigana: 'はち',
    romaji: 'hachi',
    meaning: 'eight',
  },
  {
    kanji: '二十日',
    writing: '二十日',
    furigana: 'はつか',
    romaji: 'hatsuka',
    meaning: 'the 20th of the month, 20 days',
  },
  {
    kanji: '花',
    writing: '花',
    furigana: 'はな',
    romaji: 'hana',
    meaning: 'flower',
  },
  {
    kanji: '鼻',
    writing: '鼻',
    furigana: 'はな',
    romaji: 'hana',
    meaning: 'nose',
  },
  {
    kanji: '話',
    writing: '話',
    furigana: 'はなし',
    romaji: 'hanashi',
    meaning: 'conversation, tale',
  },
  {
    kanji: '話す',
    writing: '話す',
    furigana: 'はなす',
    romaji: 'hanasu',
    meaning: 'to talk, to speak, to tell',
  },
  {
    kanji: '母',
    writing: '母',
    furigana: 'はは',
    romaji: 'haha',
    meaning: 'my mother',
  },
  {
    kanji: '早い',
    writing: '早い',
    furigana: 'はやい',
    romaji: 'hayai',
    meaning: 'early',
  },
  {
    kanji: '速い',
    writing: '速い',
    furigana: 'はやい',
    romaji: 'hayai',
    meaning: 'fast, quick',
  },
  {
    kanji: '春',
    writing: '春',
    furigana: 'はる',
    romaji: 'haru',
    meaning: 'spring',
  },
  {
    kanji: '張る',
    writing: '張る',
    furigana: 'はる',
    romaji: 'haru',
    meaning: 'to put something on, to stick',
  },
  {
    kanji: '晴れる',
    writing: '晴れる',
    furigana: 'はれる',
    romaji: 'hareru',
    meaning: 'to clear up',
  },
  {
    kanji: '〜半',
    writing: '〜半',
    furigana: '〜はん',
    romaji: '~han',
    meaning: 'Half~',
  },
  {
    kanji: '晩',
    writing: '晩',
    furigana: 'ばん',
    romaji: 'ban',
    meaning: 'evening',
  },
  {
    kanji: '~番',
    writing: '~番',
    furigana: '〜ばん',
    romaji: '~ban',
    meaning: 'No.~, ranking',
  },
  {
    kanji: 'パン',
    writing: 'パン',
    furigana: 'パン',
    romaji: 'pan',
    meaning: 'bread',
  },
  {
    kanji: 'ハンカチ',
    writing: 'ハンカチ',
    furigana: 'ハンカチ',
    romaji: 'hankachi',
    meaning: 'handkerchief',
  },
  {
    kanji: '番号',
    writing: '番号',
    furigana: 'ばんごう',
    romaji: 'bangou',
    meaning: 'number',
  },
  {
    kanji: '晩ご飯',
    writing: '晩ご飯',
    furigana: 'ばんごはん',
    romaji: 'bangohan',
    meaning: 'dinner',
  },
  {
    kanji: '半分',
    writing: '半分',
    furigana: 'はんぶん',
    romaji: 'hanbun',
    meaning: 'half',
  },

  {
    kanji: '東',
    writing: '東',
    furigana: 'ひがし',
    romaji: 'higashi',
    meaning: 'east',
  },
  {
    kanji: '〜匹',
    writing: '〜匹',
    furigana: '〜ひき',
    romaji: '~hiki',
    meaning: 'counter for animals',
  },
  {
    kanji: '引く',
    writing: '引く',
    furigana: 'ひく',
    romaji: 'hiku',
    meaning: 'to pull',
  },
  {
    kanji: '弾く',
    writing: '弾く',
    furigana: 'ひく',
    romaji: 'hiku',
    meaning: 'to play (an instrument)',
  },
  {
    kanji: '低い',
    writing: '低い',
    furigana: 'ひくい',
    romaji: 'hikui',
    meaning: ' low',
  },
  {
    kanji: '飛行機',
    writing: '飛行機',
    furigana: 'ひこうき',
    romaji: 'hikouki',
    meaning: 'plane',
  },
  {
    kanji: '左',
    writing: '左',
    furigana: 'ひだり',
    romaji: 'hidari',
    meaning: 'left',
  },
  {
    kanji: '人',
    writing: '人',
    furigana: 'ひと',
    romaji: 'hito',
    meaning: 'person',
  },
  {
    kanji: '一つ',
    writing: '一つ',
    furigana: 'ひとつ',
    romaji: 'hitotsu',
    meaning: 'one',
  },
  {
    kanji: '一月',
    writing: '一月',
    furigana: 'ひとつき',
    romaji: 'hitotsuki',
    meaning: 'one month',
  },
  {
    kanji: '一人',
    writing: '一人',
    furigana: 'ひとり',
    romaji: 'hitori',
    meaning: 'one person',
  },
  {
    kanji: '暇',
    writing: '暇',
    furigana: ' ひま',
    romaji: 'hima',
    meaning: 'free time, leisure',
  },
  {
    kanji: '百',
    writing: '百',
    furigana: 'ひゃく',
    romaji: 'hyaku',
    meaning: 'hundred',
  },
  {
    kanji: '病院',
    writing: '病院',
    furigana: 'びょういん',
    romaji: 'byouin',
    meaning: 'hospital',
  },
  {
    kanji: '病気',
    writing: '病気',
    furigana: 'びょうき',
    romaji: 'byouki',
    meaning: 'ill, sick',
  },
  {
    kanji: '平仮名',
    writing: '平仮名',
    furigana: 'ひらがな',
    romaji: 'hiragana',
    meaning: 'hiragana characters',
  },
  {
    kanji: '昼',
    writing: '昼',
    furigana: 'ひる',
    romaji: 'hiru',
    meaning: 'noon',
  },
  {
    kanji: '昼ご飯',
    writing: '昼ご飯',
    furigana: 'ひるごはん',
    romaji: 'hirugohan',
    meaning: 'lunch',
  },
  {
    kanji: '広い',
    writing: '広い',
    furigana: 'ひろい',
    romaji: 'hiroi',
    meaning: 'wide, spacious',
  },
  {
    kanji: 'フィルム',
    writing: 'フィルム',
    furigana: 'フィルム',
    romaji: 'firumu',
    meaning: 'film',
  },
  {
    kanji: '封筒',
    writing: '封筒',
    furigana: 'ふうとう',
    romaji: 'fuutou',
    meaning: 'envelope',
  },
  {
    kanji: 'プール',
    writing: 'プール',
    furigana: 'プール',
    romaji: 'puuru',
    meaning: 'pool',
  },
  {
    kanji: 'フォーク',
    writing: 'フォーク',
    furigana: 'フォーク',
    romaji: 'fooku',
    meaning: 'fork',
  },
  {
    kanji: '吹く',
    writing: '吹く',
    furigana: 'ふく',
    romaji: 'fuku',
    meaning: 'to blow (wind)',
  },
  {
    kanji: '服',
    writing: '服',
    furigana: 'ふく',
    romaji: 'fuku',
    meaning: 'clothes',
  },
  {
    kanji: '二つ',
    writing: '二つ',
    furigana: 'ふたつ',
    romaji: 'futatsu',
    meaning: 'two',
  },
  {
    kanji: '豚肉',
    writing: '豚肉',
    furigana: 'ぶたにく',
    romaji: 'butaniku',
    meaning: 'pork',
  },
  {
    kanji: '二人',
    writing: '二人',
    furigana: 'ふたり',
    romaji: 'futari',
    meaning: 'two people',
  },
  {
    kanji: '二日',
    writing: '二日',
    furigana: 'ふつか',
    romaji: 'futsuka',
    meaning: '2nd day of the month, 2 days',
  },
  {
    kanji: '太い',
    writing: '太い',
    furigana: 'ふとい',
    romaji: 'futoi',
    meaning: 'thick, fat',
  },
  {
    kanji: '降る',
    writing: '降る',
    furigana: 'ふる',
    romaji: 'furu',
    meaning: 'to fall (rain, snow)',
  },
  {
    kanji: '古い',
    writing: '古い',
    furigana: 'ふるい',
    romaji: 'furui',
    meaning: 'old',
  },
  {
    kanji: 'お風呂',
    writing: 'お風呂',
    furigana: 'おふろ',
    romaji: 'ofuro',
    meaning: 'bath',
  },
  {
    kanji: '〜分',
    writing: '〜分',
    furigana: '〜ふん',
    romaji: '~fun',
    meaning: '~minutes',
  },
  {
    kanji: 'ページ',
    writing: 'ページ',
    furigana: 'ページ',
    romaji: 'peeji',
    meaning: 'page',
  },
  {
    kanji: '下手',
    writing: '下手',
    furigana: 'へた',
    romaji: 'heta',
    meaning: 'not good at something',
  },
  {
    kanji: 'ベッド',
    writing: 'ベッド',
    furigana: 'ベッド',
    romaji: 'beddo',
    meaning: 'bed',
  },
  {
    kanji: '部屋',
    writing: '部屋',
    furigana: 'へや',
    romaji: 'heya',
    meaning: 'room',
  },
  {
    kanji: '辺',
    writing: '辺',
    furigana: 'へん',
    romaji: 'hen',
    meaning: 'side, part, area',
  },
  {
    kanji: 'ペン',
    writing: 'ペン',
    furigana: 'ぺん',
    romaji: 'pen',
    meaning: 'pen',
  },
  {
    kanji: '勉強',
    writing: '勉強',
    furigana: 'べんきょう',
    romaji: 'benkyou',
    meaning: 'to study',
  },
  {
    kanji: '便利',
    writing: '便利',
    furigana: 'べんり',
    romaji: 'benri',
    meaning: 'convenient',
  },
  {
    kanji: '方',
    writing: '方',
    furigana: 'ほう',
    romaji: 'hou',
    meaning: '~より〜のほうが〜',
  },
  {
    kanji: '帽子',
    writing: '帽子',
    furigana: 'ぼうし',
    romaji: 'boushi',
    meaning: 'hat',
  },
  {
    kanji: 'ボールペン',
    writing: 'ボールペン',
    furigana: 'ボールペン',
    romaji: 'boorupen',
    meaning: 'ballpen',
  },
  {
    kanji: '他',
    writing: '他',
    furigana: 'ほか',
    romaji: 'hoka',
    meaning: 'another, other',
  },
  {
    kanji: 'ポケット',
    writing: 'ポケット',
    furigana: 'ポケット',
    romaji: 'poketto',
    meaning: 'pocket',
  },
  {
    kanji: '欲しい',
    writing: '欲しい',
    furigana: 'ほしい',
    romaji: 'hoshii',
    meaning: 'to want something',
  },
  {
    kanji: '細い',
    writing: '細い',
    furigana: 'ほそい',
    romaji: 'hosoi',
    meaning: 'thin, fine',
  },
  {
    kanji: 'ボタン',
    writing: 'ボタン',
    furigana: 'ボタン',
    romaji: 'botan',
    meaning: 'button',
  },
  {
    kanji: 'ホテル',
    writing: 'ホテル',
    furigana: 'ホテル',
    romaji: 'hoteru',
    meaning: 'hotel',
  },
  {
    kanji: '本',
    writing: '本',
    furigana: 'ほん',
    romaji: 'hon',
    meaning: 'book',
  },
  {
    kanji: '〜本',
    writing: '〜本',
    furigana: '~ほん',
    romaji: '~hon',
    meaning: 'counter for long objects',
  },
  {
    kanji: '本棚',
    writing: '本棚',
    furigana: 'ほんだな',
    romaji: 'hondana',
    meaning: 'bookshelf',
  },
  {
    kanji: '本当に',
    writing: '本当に',
    furigana: 'ほんとうに',
    romaji: 'hontouni',
    meaning: 'really',
  },
  {
    kanji: '〜枚',
    writing: '〜枚',
    furigana: '〜まい',
    romaji: '~mai',
    meaning: 'counter for thin objects',
  },
  {
    kanji: '毎朝',
    writing: '毎朝',
    furigana: 'まいあさ',
    romaji: 'maiasa',
    meaning: 'every morning',
  },
  {
    kanji: '毎月',
    writing: '毎月',
    furigana: 'まいつき/まいげつ',
    romaji: 'maitsuki/maigetsu',
    meaning: 'every month',
  },
  {
    kanji: '毎週',
    writing: '毎週',
    furigana: 'まいしゅう',
    romaji: 'maishuu',
    meaning: 'every week',
  },
  {
    kanji: '毎日',
    writing: '毎日',
    furigana: 'まいにち',
    romaji: 'mainichi',
    meaning: 'every day',
  },
  {
    kanji: '毎年',
    writing: '毎年',
    furigana: 'まいとし/まいねん',
    romaji: 'maitoshi/mainen',
    meaning: 'every year',
  },
  {
    kanji: '毎晩',
    writing: '毎晩',
    furigana: 'まいばん',
    romaji: 'maiban',
    meaning: 'every evening',
  },
  {
    kanji: '前',
    writing: '前',
    furigana: 'まえ',
    romaji: 'mae',
    meaning: 'front',
  },
  {
    kanji: '〜前',
    writing: '〜前',
    furigana: '〜まえ',
    romaji: '~mae',
    meaning: 'before, in front of',
  },
  {
    kanji: '曲がる',
    writing: '曲がる',
    furigana: 'まがる',
    romaji: 'magaru',
    meaning: 'to turn',
  },
  {
    kanji: '不味い',
    writing: '不味い',
    furigana: 'まずい',
    romaji: 'mazui',
    meaning: 'bad tasting',
  },
  {
    kanji: 'また',
    writing: 'また',
    furigana: 'また',
    romaji: 'mata',
    meaning: 'also, again',
  },
  {
    kanji: 'まだ',
    writing: 'まだ',
    furigana: 'まだ',
    romaji: 'mada',
    meaning: 'not yet',
  },
  {
    kanji: '町',
    writing: '町',
    furigana: 'まち',
    romaji: 'machi',
    meaning: 'city, town',
  },
  {
    kanji: '待つ',
    writing: '待つ',
    furigana: 'まつ',
    romaji: 'matsu',
    meaning: 'to wait',
  },
  {
    kanji: '真直ぐに',
    writing: '真直ぐに',
    furigana: 'まっすぐに',
    romaji: 'massugu ni',
    meaning: 'straight ahead',
  },
  {
    kanji: 'マッチ',
    writing: 'マッチ',
    furigana: 'マッチ',
    romaji: 'machi',
    meaning: 'matches',
  },
  {
    kanji: '窓',
    writing: '窓',
    furigana: 'まど',
    romaji: 'mado',
    meaning: 'window',
  },
  {
    kanji: '丸い',
    writing: '丸い',
    furigana: 'まるい',
    romaji: 'marui',
    meaning: 'round',
  },
  {
    kanji: '万',
    writing: '万',
    furigana: 'まん',
    romaji: 'man',
    meaning: 'ten thousand',
  },
  {
    kanji: '万年筆',
    writing: '万年筆',
    furigana: 'まんねんひつ',
    romaji: 'mannenhitsu',
    meaning: 'fountain pen',
  },
  {
    kanji: '磨く',
    writing: '磨く',
    furigana: 'みがく',
    romaji: 'migaku',
    meaning: 'to polish, to brush',
  },
  {
    kanji: '右',
    writing: '右',
    furigana: 'みぎ',
    romaji: 'migi',
    meaning: 'right',
  },
  {
    kanji: '短い',
    writing: '短い',
    furigana: 'みじかい',
    romaji: 'mijikai',
    meaning: 'short',
  },
  {
    kanji: 'お水',
    writing: 'お水',
    furigana: 'おみず',
    romaji: 'omizu',
    meaning: 'water',
  },
  {
    kanji: '店',
    writing: '店',
    furigana: 'みせ',
    romaji: 'mise',
    meaning: 'shop',
  },
  {
    kanji: '見せる',
    writing: '見せる',
    furigana: 'みせる',
    romaji: 'miseru',
    meaning: 'to look, to watch',
  },
  {
    kanji: '道',
    writing: '道',
    furigana: 'みち',
    romaji: 'michi',
    meaning: 'road',
  },
  {
    kanji: '三日',
    writing: '三日',
    furigana: 'みっか',
    romaji: 'mikka',
    meaning: '3rd day of a month, 3 days',
  },
  {
    kanji: '三つ',
    writing: '三つ',
    furigana: 'みっつ',
    romaji: 'mittsu',
    meaning: 'three',
  },
  {
    kanji: '皆さん',
    writing: '皆さん',
    furigana: 'みなさん',
    romaji: 'minsan',
    meaning: 'everyone',
  },
  {
    kanji: '南',
    writing: '南',
    furigana: 'みなみ',
    romaji: 'minami',
    meaning: 'south',
  },
  {
    kanji: '耳',
    writing: '耳',
    furigana: 'みみ',
    romaji: 'mimi',
    meaning: 'ear',
  },
  {
    kanji: '見る',
    writing: '見る',
    furigana: 'みる',
    romaji: 'miru',
    meaning: 'to see, to watch',
  },
  {
    kanji: '皆',
    writing: '皆',
    furigana: 'みんな',
    romaji: 'minna',
    meaning: 'all, everyone',
  },
  {
    kanji: '六日',
    writing: '六日',
    furigana: 'むいか',
    romaji: 'muika',
    meaning: 'the 6th day of a month, 6 days',
  },
  {
    kanji: '向こう',
    writing: '向こう',
    furigana: 'むこう',
    romaji: 'mukou',
    meaning: 'over there',
  },
  {
    kanji: '難しい',
    writing: '難しい',
    furigana: 'むずかしい',
    romaji: 'muzukashii',
    meaning: 'difficult',
  },
  {
    kanji: '六つ',
    writing: '六つ',
    furigana: 'むっつ',
    romaji: 'muttsu',
    meaning: 'six',
  },
  {
    kanji: '目',
    writing: '目',
    furigana: 'め',
    romaji: 'me',
    meaning: 'eye',
  },
  {
    kanji: 'メートル',
    writing: 'メートル',
    furigana: 'メートル',
    romaji: 'meetoru',
    meaning: 'meter',
  },
  {
    kanji: 'めがね',
    writing: 'めがね',
    furigana: 'めがね',
    romaji: 'megane',
    meaning: 'a pair of glasses',
  },
  {
    kanji: '目',
    writing: '目',
    furigana: 'め',
    romaji: 'me',
    meaning: 'eye',
  },
  {
    kanji: 'メートル',
    writing: 'メートル',
    furigana: 'メートル',
    romaji: 'meetoru',
    meaning: 'meter',
  },
  {
    kanji: 'めがね',
    writing: 'めがね',
    furigana: 'めがね',
    romaji: 'megane',
    meaning: 'a pair of glasses',
  },
  {
    kanji: 'もう',
    writing: 'もう',
    furigana: 'もう',
    romaji: 'mou',
    meaning: 'already, yet',
  },
  {
    kanji: 'もう',
    writing: 'もう',
    furigana: 'もう',
    romaji: 'mou',
    meaning: '(one) more',
  },
  {
    kanji: '木曜日',
    writing: '木曜日',
    furigana: 'もくようび',
    romaji: 'mokuyoubi',
    meaning: 'Thursday',
  },
  {
    kanji: 'もしもし',
    writing: 'もしもし',
    furigana: 'もしもし',
    romaji: 'moshimoshi',
    meaning: 'hello on the phone',
  },
  {
    kanji: '勿論',
    writing: '勿論',
    furigana: 'もちろん',
    romaji: 'mochiron',
    meaning: 'of course',
  },
  {
    kanji: '持つ',
    writing: '持つ',
    furigana: 'もつ',
    romaji: 'motsu',
    meaning: 'to have, to own',
  },
  {
    kanji: 'もっと',
    writing: 'もっと',
    furigana: 'もっと',
    romaji: 'motto',
    meaning: 'more',
  },
  {
    kanji: '物',
    writing: '物',
    furigana: 'もの',
    romaji: 'mono',
    meaning: 'thing',
  },
  {
    kanji: '門',
    writing: '門',
    furigana: 'もん',
    romaji: 'mon',
    meaning: 'gate',
  },
  {
    kanji: '問題',
    writing: '問題',
    furigana: 'もんだい',
    romaji: 'mondai',
    meaning: 'problem, question',
  },
  {
    kanji: '〜屋',
    writing: '〜屋',
    furigana: '〜や',
    romaji: '~ya',
    meaning: 'shop. store',
  },
  {
    kanji: '八百屋',
    writing: '八百屋',
    furigana: 'やおや',
    romaji: 'yaoya',
    meaning: 'vegetable shop',
  },
  {
    kanji: '野菜',
    writing: '野菜',
    furigana: 'やさい',
    romaji: 'yasai',
    meaning: 'vegetable',
  },
  {
    kanji: '優しい',
    writing: '優しい',
    furigana: 'やさしい',
    romaji: 'yasashii',
    meaning: 'gentle',
  },
  {
    kanji: '安い',
    writing: '安い',
    furigana: 'やすい',
    romaji: 'yasui',
    meaning: 'cheap, inexpensive',
  },
  {
    kanji: '休み',
    writing: '休み',
    furigana: 'やすみ',
    romaji: 'yasumi',
    meaning: 'holiday, vacation',
  },
  {
    kanji: '休む',
    writing: '休む',
    furigana: 'やすむ',
    romaji: 'yasumu',
    meaning: 'to rest',
  },
  {
    kanji: '八つ',
    writing: '八つ',
    furigana: 'やっつ',
    romaji: 'yattsu',
    meaning: 'eight',
  },
  {
    kanji: '山',
    writing: '山',
    furigana: 'やま',
    romaji: 'yama',
    meaning: 'mountain',
  },
  {
    kanji: '',
    writing: 'やる',
    furigana: 'やる',
    romaji: 'yaru',
    meaning: 'to do',
  },
  {
    kanji: '八日',
    writing: '八日',
    furigana: 'ようか',
    romaji: 'youka',
    meaning: '8th day of the month, 8 days',
  },
  {
    kanji: '洋服',
    writing: '洋服',
    furigana: 'ようふく',
    romaji: 'youfuku',
    meaning: 'western style clothing',
  },
  {
    kanji: 'よく',
    writing: 'よく',
    furigana: 'よく',
    romaji: 'yoku',
    meaning: 'often',
  },
  {
    kanji: '横',
    writing: '横',
    furigana: 'よこ',
    romaji: 'yoko',
    meaning: 'horizontal',
  },
  {
    kanji: '四日',
    writing: '四日',
    furigana: 'よっか',
    romaji: 'yokka',
    meaning: '4th day of the month, 4 days',
  },
  {
    kanji: '四つ',
    writing: '四つ',
    furigana: 'よっつ',
    romaji: 'yottsu',
    meaning: 'four',
  },
  {
    kanji: '呼ぶ',
    writing: '呼ぶ',
    furigana: 'よぶ',
    romaji: 'yobu',
    meaning: 'to call',
  },
  {
    kanji: '読む',
    writing: '読む',
    furigana: 'よむ',
    romaji: 'yomu',
    meaning: 'to read',
  },
  {
    kanji: '夜',
    writing: '夜',
    furigana: 'よる',
    romaji: 'yoru',
    meaning: 'night',
  },
  {
    kanji: '来月',
    writing: '来月',
    furigana: 'らいげつ',
    romaji: 'raigetsu',
    meaning: 'next month',
  },
  {
    kanji: '来週',
    writing: '来週',
    furigana: 'らいしゅう',
    romaji: 'raishuu',
    meaning: 'next week',
  },
  {
    kanji: '来年',
    writing: '来年',
    furigana: 'らいねん',
    romaji: 'rainen',
    meaning: 'next year',
  },
  {
    kanji: 'ラジオ',
    writing: 'ラジオ',
    furigana: 'ラジオ',
    romaji: 'rajio',
    meaning: 'radio',
  },
  {
    kanji: '立派',
    writing: '立派',
    furigana: 'りっぱ',
    romaji: 'rippa',
    meaning: 'splendid',
  },
  {
    kanji: '留学生',
    writing: '留学生',
    furigana: 'りゅうがくせい',
    romaji: 'ryuugakusei',
    meaning: 'foreign student',
  },
  {
    kanji: '両親',
    writing: '両親',
    furigana: 'りょうしん',
    romaji: 'ryoushin',
    meaning: 'parents',
  },
  {
    kanji: '料理',
    writing: '料理',
    furigana: 'りょうり',
    romaji: 'ryouri',
    meaning: 'cooking',
  },
  {
    kanji: '旅行',
    writing: '旅行',
    furigana: 'りょこう',
    romaji: 'ryokou',
    meaning: 'travel',
  },
  {
    kanji: '',
    writing: 'れい',
    furigana: 'れい',
    romaji: 'rei',
    meaning: 'zero',
  },
  {
    kanji: '冷蔵庫',
    writing: '冷蔵庫',
    furigana: 'れいぞうこ',
    romaji: 'reizouko',
    meaning: 'refrigerator',
  },
  {
    kanji: 'レコード',
    writing: 'レコード',
    furigana: 'レコード',
    romaji: 'rekoodo',
    meaning: 'record',
  },
  {
    kanji: 'レストラン',
    writing: 'レストラン',
    furigana: 'レストラン',
    romaji: 'resutoran',
    meaning: 'restaurant',
  },
  {
    kanji: '練習',
    writing: '練習',
    furigana: 'れんしゅう',
    romaji: 'renshuu',
    meaning: 'practice',
  },
  {
    kanji: '六',
    writing: '六',
    furigana: 'ろく',
    romaji: 'roku',
    meaning: 'six',
  },
  {
    kanji: 'ワイシャツ',
    writing: 'ワイシャツ',
    furigana: 'ワイシャツ',
    romaji: 'waishatsu',
    meaning: 'white shirt',
  },
  {
    kanji: '若い',
    writing: '若い',
    furigana: 'わかい',
    romaji: 'wakai',
    meaning: 'young',
  },
  {
    kanji: '分かる',
    writing: '分かる',
    furigana: 'わかる',
    romaji: 'wakaru',
    meaning: 'to know, to understand',
  },
  {
    kanji: '忘れる',
    writing: '忘れる',
    furigana: 'わすれる',
    romaji: 'wasureru',
    meaning: 'to forget',
  },
  {
    kanji: '私',
    writing: '私',
    furigana: 'わたし',
    romaji: 'watashi',
    meaning: 'me, I',
  },
  {
    kanji: '渡す',
    writing: '渡す',
    furigana: 'わたす',
    romaji: 'watasu',
    meaning: 'to hand over',
  },
  {
    kanji: '渡る',
    writing: '渡る',
    furigana: 'わたる',
    romaji: 'wataru',
    meaning: 'to cross',
  },
  {
    kanji: '悪い',
    writing: '悪い',
    furigana: 'わるい',
    romaji: 'warui',
    meaning: 'bad',
  },
]
