// Complete list of vocabulary for the JLPT N5 – NIHONGO ICHIBAN
// https://nihongoichiban.com/2011/04/30/complete-list-of-vocabulary-for-the-jlpt-n5/

export const vocabulariesN5 = [
  {
    kanji: '',
    writing: '',
    furigana: 'ああ',
    romaji: 'ah',
    meaning: 'Ah!',
  },
  {
    kanji: '会う',
    writing: '会う',
    furigana: 'あう',
    romaji: 'au',
    meaning: 'to meet',
  },
  {
    kanji: '青い',
    writing: '青い',
    furigana: 'あおい',
    romaji: 'aoi',
    meaning: 'blue',
  },
  {
    kanji: '赤い',
    writing: '赤い',
    furigana: 'あかい',
    romaji: 'akai',
    meaning: 'red',
  },
  {
    kanji: '明るい',
    writing: '明るい',
    furigana: 'あかるい',
    romaji: 'akarui',
    meaning: 'light, bright',
  },
  {
    kanji: '秋',
    writing: '秋',
    furigana: 'あき',
    romaji: 'aki',
    meaning: 'autumn, fall',
  },
  {
    kanji: '開く',
    writing: '開く',
    furigana: 'あく',
    romaji: 'aku',
    meaning: 'open',
  },
  {
    kanji: '開ける',
    writing: '開ける',
    furigana: 'あける',
    romaji: 'akeru',
    meaning: 'to open',
  },
  {
    kanji: '',
    writing: '',
    furigana: 'あげる',
    romaji: 'ageru',
    meaning: 'to give',
  },
  {
    kanji: '朝',
    writing: '朝',
    furigana: 'あさ',
    romaji: 'asa',
    meaning: 'morning',
  },
  {
    kanji: '朝ご飯',
    writing: '朝ご飯',
    furigana: 'あさごはん',
    romaji: 'asagohan',
    meaning: 'breakfast',
  },
  {
    kanji: 'あさって',
    writing: 'あさって',
    furigana: 'あさって',
    romaji: 'asatte',
    meaning: 'the day after tomorrow',
  },
  {
    kanji: '足',
    writing: '足',
    furigana: 'あし',
    romaji: 'ashi',
    meaning: 'leg, foot',
  },
  {
    kanji: '明日',
    writing: '明日',
    furigana: 'あした',
    romaji: 'ashita',
    meaning: 'tomorrow',
  },
  {
    kanji: 'あそこ',
    writing: 'あそこ',
    furigana: 'あそこ',
    romaji: 'asoko',
    meaning: 'over there',
  },
  {
    kanji: '遊ぶ',
    writing: '遊ぶ',
    furigana: 'あそぶ',
    romaji: 'asobu',
    meaning: 'to play',
  },
  {
    kanji: '温かい',
    writing: '温かい',
    furigana: 'あたたかい',
    romaji: 'atatakai',
    meaning: 'warm',
  },
  {
    kanji: '頭',
    writing: '頭',
    furigana: 'あたま',
    romaji: 'atama',
    meaning: 'head',
  },
  {
    kanji: '新しい',
    writing: '新しい',
    furigana: 'あたらしい',
    romaji: 'atarashii',
    meaning: 'new',
  },
  {
    kanji: 'あちら',
    writing: 'あちら',
    furigana: 'あちら',
    romaji: 'achira',
    meaning: 'over there (polite)',
  },
  {
    kanji: '暑い',
    writing: '暑い',
    furigana: 'あつい',
    romaji: 'atsui',
    meaning: 'hot (air)',
  },
  {
    kanji: '厚い',
    writing: '厚い',
    furigana: 'あつい',
    romaji: 'atsui',
    meaning: 'thick',
  },
  {
    kanji: '後',
    writing: '後',
    furigana: 'あと',
    romaji: 'ato',
    meaning: 'later, after',
  },
  {
    kanji: '貴方',
    writing: '貴方',
    furigana: 'あなた',
    romaji: 'anata',
    meaning: 'you',
  },
  {
    kanji: '兄',
    writing: '兄',
    furigana: 'あに',
    romaji: 'ani',
    meaning: 'older brother',
  },
  {
    kanji: '姉',
    writing: '姉',
    furigana: 'あね',
    romaji: 'ane',
    meaning: 'older sister',
  },
  {
    kanji: 'あの',
    writing: 'あの',
    furigana: 'あの',
    romaji: 'ano',
    meaning: 'that (over there)',
  },
  {
    kanji: 'あの',
    writing: 'あの',
    furigana: 'あの',
    romaji: 'ano',
    meaning: 'well, then',
  },
  {
    kanji: 'アパート',
    writing: 'アパート',
    furigana: 'アパート',
    romaji: 'apaato',
    meaning: 'apartment',
  },
  {
    kanji: '浴びる',
    writing: '浴びる',
    furigana: 'あびる',
    romaji: 'abiru',
    meaning: 'to take a shower',
  },
  {
    kanji: '危ない',
    writing: '危ない',
    furigana: 'あぶない',
    romaji: 'abunai',
    meaning: 'dangerous',
  },
  {
    kanji: '甘い',
    writing: '甘い',
    furigana: 'あまい',
    romaji: 'amai',
    meaning: 'sweet',
  },
  {
    kanji: 'あまり',
    writing: 'あまり',
    furigana: 'あまり',
    romaji: 'amari',
    meaning: 'not so',
  },
  {
    kanji: '雨',
    writing: '雨',
    furigana: 'あめ',
    romaji: 'ame',
    meaning: 'rain',
  },
  {
    kanji: '洗う',
    writing: '洗う',
    furigana: 'あらう',
    romaji: 'arau',
    meaning: 'to wash',
  },
  {
    kanji: '有る',
    writing: '有る',
    furigana: 'ある',
    romaji: 'aru',
    meaning: 'to be, to exist',
  },
  {
    kanji: 'ある',
    writing: 'ある',
    furigana: 'ある',
    romaji: 'aru',
    meaning: 'to possess',
  },
  {
    kanji: '歩く',
    writing: '歩く',
    furigana: 'あるく',
    romaji: 'aruku',
    meaning: 'to walk',
  },
  {
    kanji: 'あれ',
    writing: 'あれ',
    furigana: 'あれ',
    romaji: 'are',
    meaning: 'that one',
  },
]
